#!/bin/bash
### Usage: qsub -N Job_Name -v FASTQ1=/path/to/read1.fastq,FASTQ2=/path/to/read2.fastq,SAMPLE=Output_Prefix_ID_Number /path/to/Align_fastq.pbs
### Output files
#PBS -e _Align2_${SAMPLE}.err
#PBS -o _Align2_${SAMPLE}.out
#PBS -l nodes=1:ppn=12,vmem=128gb
#PBS -l walltime=14-00:00:00
#PBS -l mem=128gb
#PBS -m ae

# shellcheck source=scripts/utils.sh
source "${LG3_HOME:?}/scripts/utils.sh"
source_lg3_conf

PROGRAM=${BASH_SOURCE[0]}
echo "[$(date +'%Y-%m-%d %H:%M:%S %Z')] BEGIN: $PROGRAM"
echo "Call: ${BASH_SOURCE[*]}"
echo "Script: $PROGRAM"
echo "Arguments: $*"

### Configuration
LG3_HOME=${LG3_HOME:?}
LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT:-output}
PROJECT=${PROJECT:-LG3}
EMAIL=${EMAIL:?}
LG3_SCRATCH_ROOT=${LG3_SCRATCH_ROOT:?}
LG3_DEBUG=${LG3_DEBUG:-true}
#LG3_CHASTITY_FILTERING=${LG3_CHASTITY_FILTERING:-true}

### Debug
if [[ $LG3_DEBUG ]]; then
  echo "Settings:"
  echo "- LG3_HOME=$LG3_HOME"
  echo "- LG3_OUTPUT_ROOT=$LG3_OUTPUT_ROOT"
  echo "- EMAIL=${EMAIL}"
  echo "- LG3_SCRATCH_ROOT=$LG3_SCRATCH_ROOT"
  echo "- PWD=$PWD"
  echo "- USER=$USER"
  echo "- hostname=$(hostname)"
fi

### Input
echo "Input:"
echo "- FASTQ1=${FASTQ1:?}"
echo "- FASTQ2=${FASTQ2:?}"
echo "- SAI1=${SAI1:?}"
echo "- SAI2=${SAI2:?}"
echo "- SAMPLE=${SAMPLE:?}"
echo "- PROJECT=${PROJECT:?}"
#echo "- LG3_CHASTITY_FILTERING=${LG3_CHASTITY_FILTERING}"

## Assert existance of input files
assert_file_exists "${FASTQ1}"
assert_file_exists "${FASTQ2}"
assert_file_exists "${SAI1}"
assert_file_exists "${SAI2}"

FASTQ1=$(readlink -e "${FASTQ1:?}") ## Absolute path
FASTQ2=$(readlink -e "${FASTQ2:?}") ## Absolute path
SAI1=$(readlink -e "${SAI1:?}") ## Absolute path
SAI2=$(readlink -e "${SAI2:?}") ## Absolute path

OPWD=${PWD:?}
DATE=$(date '+%Y-%m-%d %H:%M:%S')
echo "Started $PROG on $DATE as $USER"

## Assert existance of software
SH_ALIGN_FASTQ=${LG3_HOME}/scripts/Align2_fastq.sh
assert_file_executable "${SH_ALIGN_FASTQ}"

DEST="${LG3_OUTPUT_ROOT}/${PROJECT}/exomes"
make_dir "${DEST}"

WDIR=${LG3_SCRATCH_ROOT}/${SAMPLE}
make_dir "${WDIR}"
change_dir "${WDIR}"
echo "Current working directory: ${PWD}"

cp "$FASTQ1" "$FASTQ2" "${SAI1}" "${SAI2}" .

echo "Content of ${PWD}:"
ls -lrt

FQ1=$(basename "$FASTQ1")
FQ2=$(basename "$FASTQ2")
SAI1=$(basename "$SAI1")
SAI2=$(basename "$SAI2")

"${SH_ALIGN_FASTQ}" "$FQ1" "$FQ2" "$SAMPLE" "$SAI1" "$SAI2" || error "${SH_ALIGN_FASTQ}"

echo "Content of ${PWD}:"
ls -lrt

rm "$FQ1" "$FQ2" "$SAI1" "$SAI2"

echo "Content of ${PWD}:"
ls -lrt

change_dir "${OPWD}"
echo "Current working directory: ${PWD}"

echo "Content of ${WDIR}:"
ls -lrt "${WDIR}"

cp -r -p "${WDIR}" "${DEST}/"

echo "Content of ${DEST}:"
ls -lrt "${DEST}/${SAMPLE}"*

echo "Cleanup: rm ${LG3_SCRATCH_ROOT}"
rm -rf "${LG3_SCRATCH_ROOT}"

echo "End of script!"
date

echo "[$(date +'%Y-%m-%d %H:%M:%S %Z')] END: $PROGRAM"
