#!/bin/bash
### Usage: qsub -N Job_Name -v FASTQ1=/path/to/read1.fastq,FASTQ2=/path/to/read2.fastq,PREFIX=Output_Prefix_ID_Number /path/to/Align_fastq.pbs
### Output files
#PBS -e _Align_${PREFIX}.err
#PBS -o _Align_${PREFIX}.out
#PBS -l nodes=1:bigmem:ppn=12,vmem=16gb
#PBS -m ae
U=$(whoami)
DATE=$(date '+%Y-%m-%d %H:%M:%S')
NODES=$(tr '\n' ' ' < "$PBS_NODEFILE")
echo "Started $PROG on $DATE as $U"
echo "Using node(s): $NODES"
TMP=/scratch/jocostello

mkdir -p "$TMP/${PREFIX}" || { echo "Can't create scratch directory $TMP/${PREFIX}"; exit 1; }

cd "$TMP/${PREFIX}" || { echo "ERROR: Failed to set working directory to $TMP/${PREFIX}"; exit 1; }
cp "$FASTQ1" "$FASTQ2" .
FQ1=$(basename "$FASTQ1")
FQ2=$(basename "$FASTQ2")

/home/jocostello/shared/LG3_Pipeline/scripts/Align_fastq_mm9.sh "$FQ1" "$FQ2" "$PREFIX"
rm "$FQ1" "$FQ2"

cd "$TMP" || { echo "ERROR: Failed to set working directory to $TMP"; exit 1; }

cp -r -p  "$TMP/${PREFIX}" /costellolab/data1/jocostello/LG3/exomes/
rm -rf "$TMP/${PREFIX}"

echo "End of script!"
date
