#!/bin/bash
### Usage: qsub -N Job_Name -v FASTQ1=/path/to/read1.fastq,FASTQ2=/path/to/read2.fastq,PREFIX=Output_Prefix_ID_Number /path/to/Align_fastq.pbs
### Output files
#PBS -e _Align_${PREFIX}.err
#PBS -o _Align_${PREFIX}.out
#PBS -l nodes=1:ppn=12,vmem=16gb
#PBS -m ae

### Configuration
LG3_HOME=${LG3_HOME:-/home/jocostello/shared/LG3_Pipeline}
LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT:-output}
EMAIL=${EMAIL:?}
PROJECT=${PROJECT:-LG3}
LG3_SCRATCH_ROOT=${LG3_SCRATCH_ROOT:-/scratch/${USER:?}/${PBS_JOBID}}
LG3_DEBUG=${LG3_DEBUG:-true}

### Debug
if [[ $LG3_DEBUG ]]; then
  echo "LG3_HOME=$LG3_HOME"
  echo "LG3_OUTPUT_ROOT=$LG3_OUTPUT_ROOT"
  echo "EMAIL=${EMAIL}"
  echo "LG3_SCRATCH_ROOT=$LG3_SCRATCH_ROOT"
  echo "PWD=$PWD"
  echo "USER=$USER"
fi


DATE=$(date '+%Y-%m-%d %H:%M:%S')
NODES=$(tr '\n' ' ' < "$PBS_NODEFILE")
echo "Started $PROG on $DATE as $USER"
echo "Using node(s): $NODES"
TMP=${LG3_SCRATCH_ROOT}

mkdir -p "$TMP/${PREFIX}" || { echo "Can't create scratch directory $TMP/${PREFIX}"; exit 1; }

cd "$TMP/${PREFIX}" || { echo "ERROR: Failed to set working directory to $TMP/${PREFIX}"; exit 1; }
cp "$FASTQ1" "$FASTQ2" .
FQ1=$(basename "$FASTQ1")
FQ2=$(basename "$FASTQ2")

"${LG3_HOME}/scripts/Align_fastq_mm9.sh" "$FQ1" "$FQ2" "$PREFIX"
rm "$FQ1" "$FQ2"

cd "$TMP" || { echo "ERROR: Failed to set working directory to $TMP"; exit 1; }

cp -r -p  "$TMP/${PREFIX}" "${LG3_OUTPUT_ROOT}/LG3/exomes/"
rm -rf "${TMP:?}/${PREFIX}"

echo "End of script!"
date
