#!/bin/bash

source "${LG3_HOME:?}/scripts/utils.sh"
source_lg3_conf

PROGRAM=${BASH_SOURCE[0]}
echo "[$(date +'%Y-%m-%d %H:%M:%S %Z')] BEGIN: $PROGRAM"
echo "Call: ${BASH_SOURCE[*]}"
echo "Script: $PROGRAM"
echo "Arguments: $*"

### Configuration
LG3_HOME=${LG3_HOME:?}
LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT:-output}
PROJECT=${PROJECT:-LG3}
EMAIL=${EMAIL:?}
LG3_SCRATCH_ROOT=${TMPDIR:-/scratch/${SLURM_JOB_USER}/${SLURM_JOB_ID}}
LG3_CHASTITY_FILTERING=${LG3_CHASTITY_FILTERING:-true}
LG3_DEBUG=${LG3_DEBUG:-true}

### Debug
if ${LG3_DEBUG} ; then
  echo "Debug info:"
  echo "- LG3_HOME=$LG3_HOME"
  echo "- LG3_OUTPUT_ROOT=$LG3_OUTPUT_ROOT"
  echo "- EMAIL=${EMAIL}"
  echo "- LG3_SCRATCH_ROOT=$LG3_SCRATCH_ROOT"
  echo "- PWD=$PWD"
  echo "- USER=$USER"
  echo "- hostname=$(hostname)"
fi

### Input
echo "Input:"
echo "- FASTQ1=${FASTQ1:?}"
echo "- FASTQ2=${FASTQ2:?}"
echo "- SAMPLE=${SAMPLE:?}"
echo "- PATIENT=${PATIENT:?}"
echo "- PROJECT=${PROJECT:?}"
echo "- LG3_CHASTITY_FILTERING=${LG3_CHASTITY_FILTERING}"

## Assert existance of input files
assert_file_exists "${FASTQ1}"
assert_file_exists "${FASTQ2}"

FASTQ1=$(readlink -e "${FASTQ1:?}") ## Absolute path
FASTQ2=$(readlink -e "${FASTQ2:?}") ## Absolute path

OPWD=${PWD:?}
DATE=$(date '+%Y-%m-%d %H:%M:%S')
echo "Started $PROG on $DATE as $USER"
echo "Using node(s): ${SLURM_JOB_NODELIST}"
echo "SLURM_NTASKS: ${SLURM_NTASKS}"

## Assert existance of software
SH_ALIGN_FASTQ=${LG3_HOME}/scripts/Align_mem.sh
assert_file_executable "${SH_ALIGN_FASTQ}"

DEST="${LG3_OUTPUT_ROOT}/${PROJECT}/exomes_recal/${PATIENT}"
make_dir "${DEST}"

WDIR=${LG3_SCRATCH_ROOT}/${SAMPLE}
make_dir "${WDIR}"
change_dir "${WDIR}"
echo "Current working directory: ${PWD}"

cp "$FASTQ1" "$FASTQ2" .

#echo "Content of ${PWD}:"
#ls -srt

FQ1=$(basename "$FASTQ1")
FQ2=$(basename "$FASTQ2")

"${SH_ALIGN_FASTQ}" "$FQ1" "$FQ2" "$SAMPLE" || error "${SH_ALIGN_FASTQ} FAILED"

rm "$FQ1" "$FQ2"

change_dir "${OPWD}"
echo "Current working directory: ${PWD}"

echo "Content of ${WDIR}:"
ls -srt "${WDIR}"

echo "Copying results to permanent location..."
cp -p "${WDIR}/"* "${DEST}/"

echo "Cleanup: rm ${LG3_SCRATCH_ROOT}"
rm -rf "${LG3_SCRATCH_ROOT}"

echo "End of script!"
date

echo "[$(date +'%Y-%m-%d %H:%M:%S %Z')] END: $PROGRAM"
