#!/bin/bash
### Usage: qsub -N Job_Name -v FASTQ1=/path/to/read1.fastq,FASTQ2=/path/to/read2.fastq,PREFIX=Output_Prefix_ID_Number /path/to/Align_fastq.pbs
### Output files
#PBS -e _Align_${PREFIX}.err
#PBS -o _Align_${PREFIX}.out
#PBS -l nodes=1:bigmem:ppn=12,vmem=100gb
#PBS -m ae

### Configuration
LG3_HOME=${LG3_HOME:-/home/jocostello/shared/LG3_Pipeline}
LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT:-/costellolab/data1/jocostello}
SCRATCHDIR=${SCRATCHDIR:-/scratch/${USER:?}}
LG3_DEBUG=${LG3_DEBUG:-true}

### Debug
if [[ $LG3_DEBUG ]]; then
  echo "LG3_HOME=$LG3_HOME"
  echo "LG3_OUTPUT_ROOT=$LG3_OUTPUT_ROOT"
  echo "SCRATCHDIR=$SCRATCHDIR"
  echo "PWD=$PWD"
  echo "USER=$USER"
fi

### Input
FASTQ1=$(readlink -e "${FASTQ1:?}") ## Absolute path
FASTQ2=$(readlink -e "${FASTQ2:?}") ## Absolute path
echo "Input:"
echo "FASTQ1=${FASTQ1:?}"
echo "FASTQ2=${FASTQ2:?}"
echo "PREFIX=${PREFIX:?}"

OPWD=${PWD:?}
DATE=$(date '+%Y-%m-%d %H:%M:%S')
NODES=$(tr '\n' ' ' < "$PBS_NODEFILE")
echo "Started $PROG on $DATE as $USER"
echo "Using node(s): $NODES"

WDIR=${SCRATCHDIR}/${PREFIX}

mkdir -p "${WDIR}" || { echo "Can't create scratch directory ${WDIR}"; exit 1; }
cd "${WDIR}" || { echo "ERROR: Failed to set working directory to ${WDIR}"; exit 1; }
echo "Current working directory: ${PWD}"

cp "$FASTQ1" "$FASTQ2" .
FQ1=$(basename "$FASTQ1")
FQ2=$(basename "$FASTQ2")

"${LG3_HOME}/scripts/Align_fastq.sh" "$FQ1" "$FQ2" "$PREFIX"
rm "$FQ1" "$FQ2"

cd "${OPWD}" || { echo "ERROR: Failed to set working directory to .."; exit 1; }
echo "Current working directory: ${PWD}"

cp -r -p "${WDIR}" "${LG3_OUTPUT_ROOT}/LG3/exomes/"
rm -rf "${WDIR:?}"

echo "End of script!"
date
