#!/bin/bash

### Usage: qsub -N Job_Name -v BAM=/path/to/data.bam,PREFIX=Output_Prefix_ID_Number /path/to/Align_bam.pbs
### Output files
#PBS -e Align_${PREFIX}.err
#PBS -o Align_${PREFIX}.out
#PBS -l nodes=1:ppn=12
#PBS -m ae

### Configuration
LG3_HOME=${LG3_HOME:-/home/jocostello/shared/LG3_Pipeline}
LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT:-output}
EMAIL=${EMAIL:?}
PROJECT=${PROJECT:-LG3}
LG3_SCRATCH_ROOT=${LG3_SCRATCH_ROOT:-/scratch/${USER:?}/${PBS_JOBID}}
LG3_DEBUG=${LG3_DEBUG:-true}

### Debug
if [[ $LG3_DEBUG ]]; then
  echo "LG3_HOME=$LG3_HOME"
  echo "LG3_OUTPUT_ROOT=$LG3_OUTPUT_ROOT"
  echo "EMAIL=${EMAIL}"
  echo "LG3_SCRATCH_ROOT=$LG3_SCRATCH_ROOT"
  echo "PWD=$PWD"
  echo "USER=$USER"
fi



mkdir "${LG3_SCRATCH_ROOT}/${PREFIX}"

cd "${LG3_SCRATCH_ROOT}/${PREFIX}" || { echo "ERROR: Failed to set working directory to ${LG3_SCRATCH_ROOT}/${PREFIX}"; exit 1; }

"${LG3_HOME}/scripts/Align_bam.sh" "$BAM" "$PREFIX"


mv "${LG3_SCRATCH_ROOT}/${PREFIX}" "${LG3_OUTPUT_ROOT}/LG3/exomes/"

echo "End of script!"
