#!/bin/csh

### Usage: qsub -v NORMAL=AXXXXX,TUMOR=AXXXXX,RNA=AXXXXX,TYPE=TUM_or_REC1,PATIENT=XX /path/to/Annotate_RNA.pbs
### Job Name
#PBS -N RNA_Annotation
### Output files
#PBS -e Annotate_RNA.${TUMOR}.err
#PBS -o Annotate_RNA.${TUMOR}.out
### Specify which node and number of nodes
#PBS -l nodes=1:ppn=1
### Mail to user when finished
#PBS -M brett.johnson@ucsf.edu
#PBS -m e

cd /home/jocostello/LG3/exomes/Mutations/

/home/jocostello/shared/LG3_Pipeline/scripts/Annotate_RNA.sh \
	/home/jocostello/LG3/exomes/Mutations/Patient${PATIENT}.NOR-${NORMAL}__${TYPE}-${TUMOR}.annotated.mutations \
	/home/jocostello/LG3/rna/${RNA}.accepted_hits.bam \
	Patient${PATIENT}.NOR-${NORMAL}__${TYPE}-${TUMOR}

echo "End of script!"
