#!/bin/bash
HOT=false

while [ -n "$1" ]; do
case $1 in
    -hot) HOT=true;shift 1;;
    -*) echo "error: no such option $1";exit 1;;
    *)  break;;
esac
done

TRIM=true
ALIGN=false
RECAL=false
RECAL2=false
MUT=false
PINDEL=false
COMB=false
MAF=false

PROJECT=${PROJECT:-LG3}
PATIENT=${PATIENT:-Patient157t}
SAMPLES="Z00599t Z00600t Z00601t"

LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT:-/costellolab/data1/jocostello}
RAWDATA=/costellolab/data1/ismirnov/tmp
ALIGNDATA=${LG3_OUTPUT_ROOT}/${PROJECT}/exomes
RECALDATA=${LG3_OUTPUT_ROOT}/${PROJECT}/exomes_recal
MUTDATA=${LG3_OUTPUT_ROOT}/${PROJECT}/mutations
PINDELDATA=${LG3_OUTPUT_ROOT}/${PROJECT}/pindel
COMBDATA=${LG3_OUTPUT_ROOT}/${PROJECT}/MutInDel
MAFDATA=${LG3_OUTPUT_ROOT}/${PROJECT}/MAF

if ! ${HOT} ; then
	echo "Dry run!"	
fi

if ${TRIM} ; then
	echo "========== Removing trimmed data ..."
	for SAMPLE in ${SAMPLES}
	do
		echo -e "\\t${SAMPLE}"
		D="${RAWDATA}/${SAMPLE}-trim"
		du -h "${D}" || { echo "STOP"; exit 1; }
		echo -e "\\trm -rf ${D}"
		${HOT} && rm -rf "${D}" 
	done	
fi

if ${ALIGN} ; then
   echo "========== Removing aligned data ..."
   for SAMPLE in ${SAMPLES}
   do
      echo -e "\\t${SAMPLE}"
		D="${ALIGNDATA}/${SAMPLE}"
		du -h "${D}" || { echo "STOP"; exit 1; }
      echo -e "\\trm -rf ${D}"
		${HOT} && rm -rf "${D}" 
   done
fi

if ${RECAL} ; then
   echo "========== Removing recal data for ${PATIENT} ..."
	D="${RECALDATA}/${PATIENT}"
	du -h "${D}" || { echo "STOP"; exit 1; }
   echo -e "\\trm -rf ${D}"
	${HOT} && rm -rf "${D}"
fi

if ${RECAL2} ; then
   echo "========== Removing recal before.merge data for ${PATIENT} ..."
	D="${RECALDATA}/${PATIENT}.before.merge"
	du -h "${D}" || { echo "STOP"; exit 1; }
   echo -e "\\trm -rf ${D}"
	${HOT} && rm -rf "${D}"
fi

if ${MUT} ; then
   echo "========== Removing mutect data for ${PATIENT} ..."
	D="${MUTDATA}/${PATIENT}_mutect"
	du -h "${D}" || { echo "STOP"; exit 1; }
   echo -e "\\trm -rf ${D}"
	${HOT} && rm -rf "${D}"
fi

if ${PINDEL} ; then
   echo "========== Removing pindel data for ${PATIENT} ..."
	D="${PINDELDATA}/${PATIENT}_pindel"
	du -h "${D}" || { echo "STOP"; exit 1; }
   echo -e "\\trm -rf ${D}"
	${HOT} && rm -rf "${D}"
   echo -e "\\trm -f ${PINDELDATA}/${PATIENT}.pindel.cfg"
   ${HOT} && rm -rf "${D}"
fi

if ${COMB} ; then
   echo "========== Removing combined data for ${PATIENT} ..."
   echo -e "\\trm -f ${COMBDATA}/${PATIENT}.[sR]*"
	du -hc "${COMBDATA}/${PATIENT}."[sR]*
   ${HOT} && rm -rf "${D}"
fi

if ${MAF} ; then
   echo "========== Removing MAF data for ${PATIENT} ..."

	D="${MAFDATA}/${PATIENT}_MAF"
	du -h "${D}" || { echo "STOP"; exit 1; }
   echo -e "\\trm -rf ${D}"
	${HOT} && rm -rf "${D}"

	D="${MAFDATA}/${PATIENT}_plots"
	du -h "${D}" || { echo "STOP"; exit 1; }
   echo -e "\\trm -rf ${D}"
	${HOT} && rm -rf "${D}"
fi

echo "Finished!"
