#!/bin/bash
# shellcheck source=scripts/utils.sh
source "${LG3_HOME:?}/scripts/utils.sh"
assert_file_exists "${LG3_HOME}/lg3.conf"
source "${LG3_HOME}/lg3.conf"

module load jdk/1.8.0 python/2.7.15

LG3_HOME=${LG3_HOME:?}

for T in "$@"
do
	OUT="$T.help"
	${GATK4} "$T" --help true 2> "${OUT}"
	wc -l "${OUT}"
	grep EXPERIMENTAL "${OUT}"
	grep BETA "${OUT}"
done
