#!/bin/bash
# shellcheck source=scripts/utils.sh
source "${LG3_HOME:?}/scripts/utils.sh"
source_lg3_conf

module load jdk/1.8.0 python/2.7.15

doit() {
while read -r L
do
	F=$(basename $L .html)
	echo ${F##*_}
done
}

LG3_HOME=${LG3_HOME:?}
echo "Using ${GATK4?}"

GATK4PATH=$(dirname ${GATK4})
if [ $# -eq 0 ]; then
	ls ${GATK4PATH}/gatkdoc/*.html | doit | sort
fi

for T in "$@"
do
	OUT="$T.help"
	${GATK4} "$T" --help true 2> "${OUT}"
	wc -l "${OUT}"
	grep EXPERIMENTAL "${OUT}"
	grep BETA "${OUT}"
done
