#!/bin/bash

### Usage: qsub -N Job_Name -v BAMS=/path/to/file1.bam:/path/to/file2.bam:...,NORMAL=AXXXXXX,PATIENT=PatientXX,ILIST=/path/to/exome_kit.interval_list /path/to/Germline.pbs
### Output files
#PBS -e _Germline_${PATIENT}.err
#PBS -o _Germline_${PATIENT}.out
#PBS -l nodes=1:bigmem:ppn=8,vmem=200gb
#PBS -m ae

PROGRAM=${BASH_SOURCE[0]}
echo "[$(date +'%Y-%m-%d %H:%M:%S %Z')] BEGIN: $PROGRAM"
echo "Call: ${BASH_SOURCE[*]}"
echo "Script: $PROGRAM"
echo "Arguments: $*"

### Configuration
LG3_HOME=${LG3_HOME:-/home/jocostello/shared/LG3_Pipeline}
LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT:-/costellolab/data1/jocostello}
PROJECT=${PROJECT:-LG3}
EMAIL=${EMAIL:?}
SCRATCHDIR=${SCRATCHDIR:-/scratch/${USER:?}/${PBS_JOBID}}
LG3_DEBUG=${LG3_DEBUG:-true}

### Debug
if [[ $LG3_DEBUG ]]; then
  echo "LG3_HOME=$LG3_HOME"
  echo "LG3_OUTPUT_ROOT=$LG3_OUTPUT_ROOT"
  echo "EMAIL=${EMAIL}"
  echo "SCRATCHDIR=$SCRATCHDIR"
  echo "PWD=$PWD"
  echo "USER=$USER"
fi


## Input
echo "Input:"
echo "- PATIENT=${PATIENT:?}"
echo "- ILIST=${ILIST:?}"
[[ -f "$ILIST" ]] || { echo "File not found: ${ILIST}"; exit 1; }


## Software
SCRIPT=${LG3_HOME}/scripts/Germline.sh
[[ -x "$SCRIPT" ]] || { echo "File not found or not an executable: ${SCRIPT}"; exit 1; }


NODES=$(tr '\n' ' ' < "$PBS_NODEFILE")

### Updated by Ivan
### New location of recalibrated files and germline analysis output

WDIR=${LG3_OUTPUT_ROOT}/LG3/exomes_recal/${PATIENT}/germline
mkdir -p "${WDIR}" || { echo "Can't create destination directory ${WDIR}"; exit 1; }
cd "${WDIR}" || { echo "ERROR: Failed to set working directory to ${WDIR}"; exit 1; }

DATE=$(date '+%Y-%m-%d %H:%M:%S')
echo "Started $PROG on $DATE"
echo "Using node(s): $NODES"

"${SCRIPT}" \
      "${LG3_OUTPUT_ROOT}/LG3/exomes_recal/${PATIENT}/${NORMAL}.bwa.realigned.rmDups.recal.bam" \
      "${PATIENT}" \
      "$ILIST"

echo -n "End of script! "
date

echo "[$(date +'%Y-%m-%d %H:%M:%S %Z')] END: $PROGRAM"
