#!/bin/bash
PROG=Germline_only

### Usage: qsub -N Job_Name -v BAMS=/path/to/file1.bam:/path/to/file2.bam:...,NORMAL=AXXXXXX,PATIENT=PatientXX,ILIST=/path/to/exome_kit.interval_list /path/to/Germline.pbs
### Output files
#PBS -e _Germline_${PATIENT}.err
#PBS -o _Germline_${PATIENT}.out
#PBS -l nodes=1:bigmem:ppn=6
#PBS -m ae
NODES=$(tr '\n' ' ' < "$PBS_NODEFILE")

cd /home/jocostello/LG3/exomes/Mutations/ || { echo "ERROR: Failed to set working directory to /home/jocostello/LG3/exomes/Mutations/"; exit 1; }

DATE=$(date '+%Y-%m-%d %H:%M:%S')
echo "Started $PROG on $DATE"
echo "Using node(s): $NODES"

/home/jocostello/shared/LG3_Pipeline/scripts/Germline.sh \
      "/data/jocostello/LG3/exomes/${PATIENT}/${NORMAL}.bwa.realigned.rmDups.recal.bam" \
      "${PATIENT}" \
      "$ILIST"

###/home/jocostello/shared/LG3_Pipeline/resources/All_exome_targets.extended_200bp.interval_list

echo -n "End of script! "
date
