#!/bin/bash

### Usage: qsub -N Job_Name -v BAMS=/path/to/file1.bam:/path/to/file2.bam:...,PREFIX=sampleXX /path/to/Merge.pbs
### Output files
#PBS -e _Merge_${PREFIX}.err
#PBS -o _Merge_${PREFIX}.out
#PBS -l nodes=1:bigmem:ppn=6
#PBS -m ae

### Configuration
LG3_HOME=${LG3_HOME:-/home/jocostello/shared/LG3_Pipeline}
LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT:-/costellolab/data1/jocostello}
EMAIL=${EMAIL:?}
SCRATCHDIR=${SCRATCHDIR:-/scratch/${USER:?}}
LG3_DEBUG=${LG3_DEBUG:-true}

### Debug
if [[ $LG3_DEBUG ]]; then
  echo "LG3_HOME=$LG3_HOME"
  echo "LG3_OUTPUT_ROOT=$LG3_OUTPUT_ROOT"
  echo "EMAIL=${EMAIL}"
  echo "SCRATCHDIR=$SCRATCHDIR"
  echo "PWD=$PWD"
  echo "USER=$USER"
fi



date
mkdir -p "${SCRATCHDIR}/${PREFIX}"
cd "${SCRATCHDIR}/${PREFIX}" || { echo "ERROR: Failed to set working directory to ${SCRATCHDIR}/${PREFIX}"; exit 1; }

"${LG3_HOME}/scripts/Merge.sh" "$BAMS" "$PREFIX"

cd "${SCRATCHDIR}" || { echo "ERROR: Failed to set working directory to ${SCRATCHDIR}"; exit 1; }
mkdir -p "${LG3_OUTPUT_ROOT}/LG3/exomes/${PREFIX}"
cp -p "${SCRATCHDIR}/${PREFIX}"/* "${LG3_OUTPUT_ROOT}/LG3/exomes/${PREFIX}"
rm -rf "${SCRATCHDIR:?}/${PREFIX}"

echo "End of script!"
date
