#!/bin/bash

### Usage: qsub -N Job_Name -v BAMS=/path/to/file1.bam:/path/to/file2.bam:...,SAMPLE=sampleXX /path/to/Merge.pbs
### Output files
#PBS -e _MergeQC_${SAMPLE}.err
#PBS -o _MergeQC_${SAMPLE}.out
#PBS -l nodes=1:ppn=6,vmem=40gb
#PBS -m ae

# shellcheck source=scripts/utils.sh
source "${LG3_HOME}/scripts/utils.sh"
source_lg3_conf

PROGRAM=${BASH_SOURCE[0]}
echo "[$(date +'%Y-%m-%d %H:%M:%S %Z')] BEGIN: $PROGRAM"
echo "Call: ${BASH_SOURCE[*]}"
echo "Script: $PROGRAM"
echo "Arguments: $*"

### Configuration
LG3_HOME=${LG3_HOME:?}
LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT:-output}
EMAIL=${EMAIL:?}
LG3_SCRATCH_ROOT=${LG3_SCRATCH_ROOT:-/scratch/${USER:?}/${PBS_JOBID}}
LG3_DEBUG=${LG3_DEBUG:-true}

### Debug
if [[ $LG3_DEBUG ]]; then
  echo "Settings:"
  echo "- LG3_HOME=$LG3_HOME"
  echo "- LG3_OUTPUT_ROOT=$LG3_OUTPUT_ROOT"
  echo "- EMAIL=${EMAIL}"
  echo "- LG3_SCRATCH_ROOT=$LG3_SCRATCH_ROOT"
  echo "- PWD=$PWD"
  echo "- USER=$USER"
  echo "- PBS_NUM_PPN=$PBS_NUM_PPN"
  echo "- hostname=$(hostname)"
fi

### Input
echo "Input:"
echo "- PATIENT=${PATIENT:?}"
echo "- BAMS=${BAMS:?}"
echo "- SAMPLE=${SAMPLE:?}"
echo "- INTERVAL=${INTERVAL:?}"

assert_patient_name "${PATIENT}"
assert_file_exists "${INTERVAL}"

date
make_dir "${LG3_SCRATCH_ROOT}/${SAMPLE}"
change_dir "${LG3_SCRATCH_ROOT}/${SAMPLE}"

"${LG3_HOME}/scripts/Merge_QC.sh" "$BAMS" "$SAMPLE" "${INTERVAL}"

change_dir "${LG3_SCRATCH_ROOT}"

cp -a "${LG3_SCRATCH_ROOT}/${SAMPLE}"/* "${LG3_OUTPUT_ROOT}/${PROJECT}/exomes_recal/${PATIENT}" || error "Failed to copy data from ${LG3_SCRATCH_ROOT}/${SAMPLE}"

echo "Cleaning: rm ${LG3_SCRATCH_ROOT} ..."
rm -rf "${LG3_SCRATCH_ROOT:?}/${SAMPLE}"

echo "Output: ${LG3_OUTPUT_ROOT}/${PROJECT}/exomes_recal/${PATIENT}"

echo "[$(date +'%Y-%m-%d %H:%M:%S %Z')] END: $PROGRAM"
