#!/bin/bash

### Usage: qsub -N Job_Name -v BAMS=/path/to/file1.bam:/path/to/file2.bam:...,SAMPLE=sampleXX /path/to/Merge.pbs
### Output files
#PBS -e _Merge_${SAMPLE}.err
#PBS -o _Merge_${SAMPLE}.out
#PBS -l nodes=1:bigmem:ppn=6,vmem=32gb
#PBS -m ae

PROGRAM=${BASH_SOURCE[0]}
echo "[$(date +'%Y-%m-%d %H:%M:%S %Z')] BEGIN: $PROGRAM"
echo "Call: ${BASH_SOURCE[*]}"
echo "Script: $PROGRAM"
echo "Arguments: $*"

### Configuration
LG3_HOME=${LG3_HOME:-/home/jocostello/shared/LG3_Pipeline}
LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT:-output}
PROJECT=${PROJECT:-LG3}
EMAIL=${EMAIL:?}
LG3_SCRATCH_ROOT=${LG3_SCRATCH_ROOT:-/scratch/${USER:?}/${PBS_JOBID}}
LG3_DEBUG=${LG3_DEBUG:-true}

### Debug
if [[ $LG3_DEBUG ]]; then
  echo "Settings:"
  echo "- LG3_HOME=$LG3_HOME"
  echo "- LG3_OUTPUT_ROOT=$LG3_OUTPUT_ROOT"
  echo "- EMAIL=${EMAIL}"
  echo "- LG3_SCRATCH_ROOT=$LG3_SCRATCH_ROOT"
  echo "- PWD=$PWD"
  echo "- USER=$USER"
  echo "- PBS_NUM_PPN=$PBS_NUM_PPN"
  echo "- hostname=$(hostname)"
fi

### Input
echo "Input:"
echo "- BAMS=${BAMS:?}"
echo "- SAMPLE=${SAMPLE:?}"
#echo "- ILIST=${ILIST:?}"

#[[ -f "$ILIST" ]] || { echo "File not found: ${ILIST}"; exit 1; }

date

WDIR=${LG3_SCRATCH_ROOT}/${SAMPLE}
mkdir -p "${WDIR}" || { echo "Can't create scratch directory ${WDIR}"; exit 1; }
cd "${WDIR}" || { echo "ERROR: Failed to set working directory to ${WDIR}"; exit 1; }
echo "Current working directory: ${PWD}"

"${LG3_HOME}/scripts/Merge.sh" "$BAMS" "$SAMPLE"

cd "${LG3_SCRATCH_ROOT}" || { echo "ERROR: Failed to set working directory to ${LG3_SCRATCH_ROOT}"; exit 1; }

cp -a "${LG3_SCRATCH_ROOT}/${SAMPLE}"/* "${LG3_OUTPUT_ROOT}/LG3/exomes_recal/${PATIENT}" || { echo "ERROR: Failed to copy data from ${LG3_SCRATCH_ROOT}/${SAMPLE}"; exit 1; }
rm -rf "${LG3_SCRATCH_ROOT:?}/${SAMPLE}"

echo "Output: ${LG3_OUTPUT_ROOT}/LG3/exomes_recal/${PATIENT}"
echo "End of script!"
date

echo "[$(date +'%Y-%m-%d %H:%M:%S %Z')] END: $PROGRAM"
