#!/bin/bash

### Usage: qsub -N Job_Name -v BAMS=/path/to/file1.bam:/path/to/file2.bam:...,SAMPLE=sampleXX /path/to/Merge.pbs
#PBS -l nodes=1:ppn=6,vmem=32gb

source "${LG3_HOME:?}/scripts/utils.sh"
source_lg3_conf

PROGRAM=${BASH_SOURCE[0]}
echo "[$(date +'%Y-%m-%d %H:%M:%S %Z')] BEGIN: $PROGRAM"
echo "Call: ${BASH_SOURCE[*]}"
echo "Script: $PROGRAM"
echo "Arguments: $*"

### Configuration
LG3_HOME=${LG3_HOME:?}
LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT:-output}
PROJECT=${PROJECT:-LG3}
EMAIL=${EMAIL:?}
LG3_SCRATCH_ROOT=${TMPDIR:-/scratch/${SLURM_JOB_USER}/${SLURM_JOB_ID}}
LG3_DEBUG=${LG3_DEBUG:-true}

### Debug
if $LG3_DEBUG ; then
  echo "Debug info:"
  echo "- LG3_HOME=$LG3_HOME"
  echo "- LG3_OUTPUT_ROOT=$LG3_OUTPUT_ROOT"
  echo "- EMAIL=${EMAIL}"
  echo "- LG3_SCRATCH_ROOT=$LG3_SCRATCH_ROOT"
  echo "- PWD=$PWD"
  echo "- USER=$USER"
  echo "- PBS_NUM_PPN=$PBS_NUM_PPN"
  echo "- hostname=$(hostname)"
  echo "- node(s): ${SLURM_JOB_NODELIST}"
  echo "- SLURM_NTASKS: ${SLURM_NTASKS}"
fi

### Input
echo "Input:"
echo "- PATIENT=${PATIENT:?}"
echo "- BAMS=${BAMS:?}"
echo "- SAMPLE=${SAMPLE:?}"

assert_patient_name "${PATIENT}"

date

WDIR=${LG3_SCRATCH_ROOT}/${SAMPLE}
make_dir "${WDIR}"
change_dir "${WDIR}"
echo "Current working directory: ${PWD}"

"${LG3_HOME}/scripts/Merge.sh" "$BAMS" "$SAMPLE"

change_dir "${LG3_SCRATCH_ROOT}"

cp -a "${LG3_SCRATCH_ROOT}/${SAMPLE}"/* "${LG3_OUTPUT_ROOT}/${PROJECT}/exomes_recal/${PATIENT}" || error "Failed to copy data from ${LG3_SCRATCH_ROOT}/${SAMPLE}"

echo "Cleaning: rm ${LG3_SCRATCH_ROOT} ..."
rm -rf "${LG3_SCRATCH_ROOT:?}/${SAMPLE}"

echo "Output: ${LG3_OUTPUT_ROOT}/${PROJECT}/exomes_recal/${PATIENT}"
echo "End of script!"
date

echo "[$(date +'%Y-%m-%d %H:%M:%S %Z')] END: $PROGRAM"
