#!/bin/bash

source "${LG3_HOME:?}/scripts/utils.sh"
source_lg3_conf

PROGRAM=${BASH_SOURCE[0]}
echo "[$(date +'%Y-%m-%d %H:%M:%S %Z')] BEGIN: $PROGRAM"
echo "Call: ${BASH_SOURCE[*]}"
echo "Script: $PROGRAM"
echo "Arguments: $*"

### Configuration
LG3_HOME=${LG3_HOME:?}
LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT:-output}
LG3_INPUT_ROOT=${LG3_INPUT_ROOT:-${LG3_OUTPUT_ROOT}}
PROJECT=${PROJECT:?}
EMAIL=${EMAIL:?}
LG3_SCRATCH_ROOT=${TMPDIR:-/scratch/${SLURM_JOB_USER}/${SLURM_JOB_ID}}
LG3_DEBUG=${LG3_DEBUG:-true}

### Debug
if $LG3_DEBUG ; then
  echo "Debug info::"
  echo "- LG3_HOME=$LG3_HOME"
  echo "- LG3_INPUT_ROOT=$LG3_INPUT_ROOT"
  echo "- LG3_OUTPUT_ROOT=$LG3_OUTPUT_ROOT"
  echo "- EMAIL=${EMAIL}"
  echo "- PROJECT=${PROJECT}"
  echo "- LG3_SCRATCH_ROOT=$LG3_SCRATCH_ROOT"
  echo "- PWD=$PWD"
  echo "- USER=$USER"
  echo "- hostname=$(hostname)"
fi

assert_directory_exists "${LG3_INPUT_ROOT}"
LG3_INPUT_ROOT=$(readlink -e "${LG3_INPUT_ROOT:?}") ## Absolute path

### Input
echo "Input:"
echo "- PATIENT=${PATIENT:?}"
echo "- TUMOR=${TUMOR:?}"
echo "- NORMAL=${NORMAL:?}"
echo "- TYPE=${TYPE:?}"
echo "- CONFIG=${CONFIG:?}"
echo "- INTERVAL=${INTERVAL:?}"
echo "- XMX=${XMX:?}"
echo "- WORKDIR=${WORKDIR:?}"
assert_patient_name "${PATIENT}"
BAMDIR=${LG3_INPUT_ROOT}/${PROJECT}/exomes_recal
assert_directory_exists "${BAMDIR}"
assert_file_exists "${CONFIG}"
assert_file_exists "${INTERVAL}"
CONFIG=$(readlink -e "${CONFIG:?}") ## Absolute path
INTERVAL=$(readlink -e "${INTERVAL:?}") ## Absolute path

### Software
SH_MUTDET=${LG3_HOME}/scripts/MutDet.sh
assert_file_executable "${SH_MUTDET}"

BAMN=$BAMDIR/${PATIENT}/${NORMAL}.bwa.realigned.rmDups.recal.bam
BAMT=$BAMDIR/${PATIENT}/${TUMOR}.bwa.realigned.rmDups.recal.bam

assert_file_exists "${BAMN}"
assert_file_exists "${BAMT}"

SCRATCH="${LG3_SCRATCH_ROOT}/${PATIENT}_mutect"
make_dir "${SCRATCH}"
change_dir "${SCRATCH}"

echo -n "Starting MutDet job on "
date
echo "Using node(s): ${SLURM_JOB_NODELIST}"
echo "SLURM_NTASKS: ${SLURM_NTASKS}"
echo "Patient = $PATIENT"
echo "Normal = $BAMN"
echo "Tumor = $BAMT"
echo "Tum. Type = $TYPE"
echo "Config = $CONFIG"
echo "Interval = $INTERVAL"
echo "Java Memory = $XMX"
echo "WORKDIR=$WORKDIR"
echo "SCRATCH=${SCRATCH}"

"${SH_MUTDET}" \
  "$BAMN" \
  "$BAMT" \
  "NOR-${NORMAL}__${TYPE}-${TUMOR}" \
  "${PATIENT}" \
  "${CONFIG}" \
  "${INTERVAL}" \
  "$XMX" || error "MutDet failed"

make_dir "${WORKDIR}"
echo "Copy results from ${SCRATCH} to ${WORKDIR}"
cp -p "${SCRATCH}"/* "${WORKDIR}" || error "Fail to copy results to ${WORKDIR}"

echo "Cleaning: rm ${LG3_SCRATCH_ROOT} ..."
rm -rf "${LG3_SCRATCH_ROOT}"

echo "End of PBS script!"
echo "[$(date +'%Y-%m-%d %H:%M:%S %Z')] END: $PROGRAM"
