#!/bin/bash

### Usage: qsub -v NORMAL=LibraryName,TUMOR=LibraryName,TYPE=TUM_or_REC1,PATIENT=XX,CONFIG=/path/to/mutationconfig.cfg,INTERVAL=/path/to/Interval_List ${LG3_HOME}/MutDet.pbs
### Use Config: ${LG3_HOME}/FilterMutations/mutationConfig.cfg
### Use Interval: ${LG3_HOME}/resources/All_exome_targets.extended_200bp.interval_list 
### Output files
#PBS -e MutDet.${PATIENT}.NOR-${NORMAL}__${TYPE}-${TUMOR}.err
#PBS -o MutDet.${PATIENT}.NOR-${NORMAL}__${TYPE}-${TUMOR}.out
#PBS -N MutDet
#PBS -l nodes=1:ppn=4,vmem=42g
#PBS -m ae

### Configuration
LG3_HOME=${LG3_HOME:-/home/jocostello/shared/LG3_Pipeline}
LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT:-/costellolab/data1/jocostello}
SCRATCHDIR=${SCRATCHDIR:-/scratch/${USER:?}}
LG3_DEBUG=${LG3_DEBUG:-true}

### Debug
if [[ $LG3_DEBUG ]]; then
  echo "LG3_HOME=$LG3_HOME"
  echo "LG3_OUTPUT_ROOT=$LG3_OUTPUT_ROOT"
  echo "SCRATCHDIR=$SCRATCHDIR"
  echo "PWD=$PWD"
  echo "USER=$USER"
fi



BAMDIR=${LG3_OUTPUT_ROOT}/LG3/exomes_recal
mkdir -p "$WORKDIR"
cd "$WORKDIR" || { echo "ERROR: Failed to set working directory to ${WORKDIR}"; exit 1; }
echo "*** Working directory: $WORKDIR"

### For Recal
BAMN=$BAMDIR/${PATIENT}/${NORMAL}.bwa.realigned.rmDups.recal.bam
BAMT=$BAMDIR/${PATIENT}/${TUMOR}.bwa.realigned.rmDups.recal.bam

### For Recal2
#BAMN=$BAMDIR/${PATIENT}/${NORMAL}.bwa.realigned.rmDups.bam
#BAMT=$BAMDIR/${PATIENT}/${TUMOR}.bwa.realigned.rmDups.bam

if [ ! -f "$BAMN" ] || [ ! -f "$BAMT" ]; then
	echo "ERROR: BAM file(s) not found"
	echo "Expected Normal: $BAMN"
	echo "Expected Tumor: $BAMT"
	exit 1
fi
echo -n "Starting MutDet job on "
date
echo "Patient = $PATIENT"
echo "Normal = $BAMN"
echo "Tumor = $BAMT"
echo "Tum. Type = $TYPE"
echo "Config = $CONFIG"
echo "Interval = $INTERVAL"
echo "Java Memory = $XMX"
echo "WORKDIR=$WORKDIR"

"${LG3_HOME}/scripts/MutDet.sh" \
	"$BAMN" \
	"$BAMT" \
	"NOR-${NORMAL}__${TYPE}-${TUMOR}" \
	"${PATIENT}" \
	"${CONFIG}" \
	"${INTERVAL}" \
	"$XMX"

echo "End of PBS script!"
date

