#!/bin/bash

### Usage: qsub -N Job_Name -v BAMS=/path/to/file1.bam:/path/to/file2.bam:...,NORMAL=AXXXXXX,PATIENT=PatientXX,ILIST=/path/to/exome_kit.interval_list /path/to/Recal.pbs
### Output files
#PBS -e _Recal_${PATIENT}.err
#PBS -o _Recal_${PATIENT}.out
#PBS -l nodes=1:bigmem:ppn=6
#PBS -m ae

### Configuration
LG3_HOME=${LG3_HOME:-/home/jocostello/shared/LG3_Pipeline}
LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT:-output}
PROJECT=${PROJECT:-LG3}
EMAIL=${EMAIL:?}
LG3_SCRATCH_ROOT=${LG3_SCRATCH_ROOT:-/scratch/${USER:?}/${PBS_JOBID}}
LG3_DEBUG=${LG3_DEBUG:-true}

### Debug
if [[ $LG3_DEBUG ]]; then
  echo "LG3_HOME=$LG3_HOME"
  echo "LG3_OUTPUT_ROOT=$LG3_OUTPUT_ROOT"
  echo "EMAIL=${EMAIL}"
  echo "LG3_SCRATCH_ROOT=$LG3_SCRATCH_ROOT"
  echo "PWD=$PWD"
  echo "USER=$USER"
fi



date
mkdir -p "${LG3_SCRATCH_ROOT}/${PATIENT}"
cd "${LG3_SCRATCH_ROOT}/${PATIENT}" || { echo "ERROR: Failed to set working directory to ${LG3_SCRATCH_ROOT}/${PATIENT}"; exit 1; }

"${LG3_HOME}/scripts/Recal_bigmem.sh" "$BAMS" "$PATIENT" "$ILIST"

cd "${LG3_SCRATCH_ROOT}" || { echo "ERROR: Failed to set working directory to ${LG3_SCRATCH_ROOT}"; exit 1; }
cp -r -p  "${LG3_SCRATCH_ROOT}/${PATIENT}" "${LG3_OUTPUT_ROOT}/LG3/exomes_recal/"
rm "${LG3_SCRATCH_ROOT}/${PATIENT}"

echo -n "End of script! "
date
