#!/bin/bash
#PBS -e _RecalW_${Z}.err
#PBS -o _RecalW_${Z}.out
#PBS -l nodes=1:bigmem:ppn=12,vmem=200gb
#PBS -m ae

### Configuration
LG3_HOME=${LG3_HOME:-/home/jocostello/shared/LG3_Pipeline}
LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT:-/costellolab/data1/jocostello}
PROJECT=${PROJECT:-LG3}
EMAIL=${EMAIL:?}
SCRATCH_ROOT=${SCRATCH_ROOT:-/scratch/${USER:?}/${PBS_JOBID}}
LG3_DEBUG=${LG3_DEBUG:-true}

### Debug
if [[ $LG3_DEBUG ]]; then
  echo "LG3_HOME=$LG3_HOME"
  echo "LG3_OUTPUT_ROOT=$LG3_OUTPUT_ROOT"
  echo "EMAIL=${EMAIL}"
  echo "SCRATCH_ROOT=$SCRATCH_ROOT"
  echo "PWD=$PWD"
  echo "USER=$USER"
fi



### Updated by Ivan

DATE=$(date '+%Y-%m-%d %H:%M:%S')
NODES=$(tr '\n' ' ' < "$PBS_NODEFILE")
echo "Started $PROG on $DATE"
echo "Using node(s): $NODES"

BN=$(basename "$BAMS" .bam)
Z=${BN%%.*}

mkdir -p "${SCRATCH_ROOT}/${Z}"

cd "${SCRATCH_ROOT}/${Z}" || { echo "ERROR: Failed to set working directory to ${SCRATCH_ROOT}/${Z}"; exit 1; }

"${LG3_HOME}/scripts/Recal_WGS.sh" "$BAMS" "$ILIST"

cd "${SCRATCH_ROOT}" || { echo "ERROR: Failed to set working directory to ${SCRATCH_ROOT}"; exit 1; }

mkdir -p "${LG3_OUTPUT_ROOT}/LG3/exomes_recal/${Z}"
cp -p "${SCRATCH_ROOT}/${Z}"/* "${LG3_OUTPUT_ROOT}/LG3/exomes_recal/${PATIENT}" || { echo "ERROR cp!" ; exit 1 ; }
rm -rf "${SCRATCH_ROOT:?}/${Z}"

echo -n "End of PBS script! "
date
