#!/bin/bash
### Usage: qsub -N Job_Name -v BAMS=/path/to/file1.bam:/path/to/file2.bam:...,NORMAL=AXXXXXX,PATIENT=PatientXX,ILIST=/path/to/exome_kit.interval_list /path/to/Recal.pbs
### Output files
#PBS -e _Recal_${PATIENT}.err
#PBS -o _Recal_${PATIENT}.out
#PBS -l nodes=1:bigmem:ppn=12,vmem=200gb
#PBS -m ea

### Configuration
LG3_HOME=${LG3_HOME:-/home/jocostello/shared/LG3_Pipeline}
LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT:-/costellolab/data1/jocostello}
EMAIL=${EMAIL:?}
SCRATCHDIR=${SCRATCHDIR:-/scratch/${USER:?}}
LG3_DEBUG=${LG3_DEBUG:-true}

### Debug
if [[ $LG3_DEBUG ]]; then
  echo "LG3_HOME=$LG3_HOME"
  echo "LG3_OUTPUT_ROOT=$LG3_OUTPUT_ROOT"
  echo "EMAIL=${EMAIL}"
  echo "SCRATCHDIR=$SCRATCHDIR"
  echo "PWD=$PWD"
  echo "USER=$USER"
fi



### Updated by Ivan
### New location of recalibrated files and germline analysis output

DATE=$(date '+%Y-%m-%d %H:%M:%S')
NODES=$(tr '\n' ' ' < "$PBS_NODEFILE")
echo "Started $PROG on $DATE"
echo "Using node(s): $NODES"
mkdir -p "${SCRATCHDIR}/${PATIENT}"

cp "$MERGE/$PATIENT.merged.realigned.rmDups.recal."* "${SCRATCHDIR}/${PATIENT}"
cd "${SCRATCHDIR}/${PATIENT}" || { echo "ERROR: Failed to set working directory to ${SCRATCHDIR}/${PATIENT}"; exit 1; }


"${LG3_HOME}/scripts/Recal_split.sh" "$BAMS" "$PATIENT" "$ILIST"

cd "${SCRATCHDIR}" || { echo "ERROR: Failed to set working directory to ${SCRATCHDIR}"; exit 1; }

mkdir -p "${LG3_OUTPUT_ROOT}/LG3/exomes_recal/${PATIENT}"
cp -p "${SCRATCHDIR}/${PATIENT}"/* "${LG3_OUTPUT_ROOT}/LG3/exomes_recal/${PATIENT}" || { echo "ERROR cp!" ; exit 1 ; }

mkdir -p "${LG3_OUTPUT_ROOT}/LG3/exomes_recal/${PATIENT}/germline"
cd "${LG3_OUTPUT_ROOT}/LG3/exomes_recal/${PATIENT}/germline" || { echo "ERROR: Failed to set working directory to ${LG3_OUTPUT_ROOT}/LG3/exomes_recal/${PATIENT}/germline"; exit 1; }

"${LG3_HOME}/scripts/Germline.sh" \
      "${LG3_OUTPUT_ROOT}/LG3/exomes_recal/${PATIENT}/${NORMAL}.bwa.realigned.rmDups.recal.bam" \
      "${PATIENT}" "$ILIST"

echo -n "End of script! "
date
