#!/bin/bash
#PBS -e _RecalW_${Z}.err
#PBS -o _RecalW_${Z}.out
#PBS -l nodes=1:bigmem:ppn=12,vmem=200gb
#PBS -m ae

### Configuration
LG3_HOME=${LG3_HOME:-/home/jocostello/shared/LG3_Pipeline}
LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT:-/costellolab/data1/jocostello}
EMAIL=${EMAIL:?}
SCRATCHDIR=${SCRATCHDIR:-/scratch/${USER:?}}
LG3_DEBUG=${LG3_DEBUG:-true}

### Debug
if [[ $LG3_DEBUG ]]; then
  echo "LG3_HOME=$LG3_HOME"
  echo "LG3_OUTPUT_ROOT=$LG3_OUTPUT_ROOT"
  echo "EMAIL=${EMAIL}"
  echo "SCRATCHDIR=$SCRATCHDIR"
  echo "PWD=$PWD"
  echo "USER=$USER"
fi



### Updated by Ivan

DATE=$(date '+%Y-%m-%d %H:%M:%S')
NODES=$(tr '\n' ' ' < "$PBS_NODEFILE")
echo "Started $PROG on $DATE"
echo "Using node(s): $NODES"

#BN=$(basename $BAMS .bam)
#Z=${BN%%.*}

#mkdir -p ${SCRATCHDIR}/${Z}

#cd ${SCRATCHDIR}/${Z}

"${LG3_HOME}/scripts/Recal_WGS_QC.sh" "$BAMS" "$ILIST"

#cd ${SCRATCHDIR}

#mkdir -p "${LG3_OUTPUT_ROOT}/LG3/exomes_recal/${Z}"
#cp -p ${SCRATCHDIR}/${Z}/* "${LG3_OUTPUT_ROOT}/LG3/exomes_recal/${PATIENT}" || { echo "ERROR cp!" ; exit 1 ; }
#rm -rf ${SCRATCHDIR}/${Z}

echo -n "End of PBS script! "
date
