#!/bin/bash
### Usage: qsub -N Job_Name -v BAMS=/path/to/file1.bam:/path/to/file2.bam:...,NORMAL=AXXXXXX,PATIENT=PatientXX,ILIST=/path/to/exome_kit.interval_list /path/to/Recal.pbs
#PBS -e _Recal_${PATIENT}.err
#PBS -o _Recal_${PATIENT}.out
#PBS -l nodes=1:ppn=12,vmem=200gb
#PBS -m ae

# shellcheck source=scripts/utils.sh
source "${LG3_HOME}/scripts/utils.sh"

PROGRAM=${BASH_SOURCE[0]}
echo "[$(date +'%Y-%m-%d %H:%M:%S %Z')] BEGIN: $PROGRAM"
echo "Call: ${BASH_SOURCE[*]}"
echo "Script: $PROGRAM"
echo "Arguments: $*"

### Configuration
LG3_HOME=${LG3_HOME:?}
LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT:-output}
EMAIL=${EMAIL:?}
PROJECT=${PROJECT:-LG3}
LG3_SCRATCH_ROOT=${LG3_SCRATCH_ROOT:-/scratch/${USER:?}/${PBS_JOBID}}
LG3_DEBUG=${LG3_DEBUG:-true}

### Debug
if [[ $LG3_DEBUG ]]; then
  echo "Settings:"
  echo "- LG3_HOME=$LG3_HOME"
  echo "- LG3_OUTPUT_ROOT=$LG3_OUTPUT_ROOT"
  echo "- EMAIL=${EMAIL}"
  echo "- LG3_SCRATCH_ROOT=$LG3_SCRATCH_ROOT"
  echo "- PWD=$PWD"
  echo "- USER=$USER"
  echo "- PBS_NUM_PPN=$PBS_NUM_PPN"
  echo "- hostname=$(hostname)"
fi


### Input
echo "Input:"
echo "- PROJECT=${PROJECT:?}"
echo "- BAMS=${BAMS:?}"
echo "- PATIENT=${PATIENT:?}"
echo "- NORMAL=${NORMAL:?}"
echo "- ILIST=${ILIST:?}"

assert_patient_name "${PATIENT}"

## Assert existance of input files
assert_file_exists "${ILIST}"
ILIST=$(readlink -e "${ILIST:?}") ## Absolute path

module load CBC r/3.4.2

echo -n "Checking R: "
Rscript --version || error "No Rscript is available!"

DATE=$(date '+%Y-%m-%d %H:%M:%S')
NODES=$(tr '\n' ' ' < "$PBS_NODEFILE")
echo "Started $PROG on $DATE"
echo "Using node(s): $NODES"

## Assert existance of software
SH_RECAL=${LG3_HOME}/scripts/Recal_bigmem.sh
assert_file_executable "${SH_RECAL}"

SH_GERMLINE=${LG3_HOME}/scripts/Germline.sh
assert_file_executable "${SH_GERMLINE}"

DESTDIR=${LG3_OUTPUT_ROOT}/${PROJECT}/exomes_recal/${PATIENT}
mkdir -p "${DESTDIR}" || error "Can't create destination directory ${DESTDIR}"

DESTDIR2=${LG3_OUTPUT_ROOT}/${PROJECT}/exomes_recal/${PATIENT}/germline
mkdir -p "${DESTDIR2}" || error "Can't create destination directory ${DESTDIR2}"

WDIR=${LG3_SCRATCH_ROOT}/${PATIENT}
mkdir -p "${WDIR}" || error "Can't create destination directory ${WDIR}"
cd "${WDIR}" || error "Failed to set working directory to ${WDIR}"

"${SH_RECAL}" "$BAMS" "$PATIENT" "$ILIST" || error "${SH_RECAL} failed"

cd "${LG3_SCRATCH_ROOT}" || error "Failed to set working directory to ${LG3_SCRATCH_ROOT}"

cp -p "${LG3_SCRATCH_ROOT}/${PATIENT}"/* "${DESTDIR}" || error "cp 1"

echo "Starting germline analysis ..."
WDIR2=${LG3_SCRATCH_ROOT}/${PATIENT}/germline

mkdir -p "${WDIR2}" || error "Can't create destination directory ${WDIR2}"

cd "${WDIR2}" || error "Failed to set working directory to ${WDIR2}"

[[ -f "../${NORMAL}.bwa.realigned.rmDups.recal.bam" ]] || error "File not found: ../${NORMAL}.bwa.realigned.rmDups.recal.bam"

{ time "${SH_GERMLINE}" \
      "../${NORMAL}.bwa.realigned.rmDups.recal.bam" \
      "${PATIENT}" "$ILIST"; } 2>&1 || error "${SH_GERMLINE} failed"

cp -p "${LG3_SCRATCH_ROOT}/${PATIENT}"/germline/* "${DESTDIR2}" || error "cp 2"

echo "Cleaning: rm ${LG3_SCRATCH_ROOT} ..."
rm -rf "${LG3_SCRATCH_ROOT}"

echo "[$(date +'%Y-%m-%d %H:%M:%S %Z')] END: $PROGRAM"
