#!/bin/bash
#PBS -e _RecalW_${Z}.err
#PBS -o _RecalW_${Z}.out
#PBS -l nodes=1:bigmem:ppn=12,vmem=200gb
#PBS -m ea -M ivan.smirnov@ucsf.edu

### Updated by Ivan

U=$(whoami)
DATE=$(date '+%Y-%m-%d %H:%M:%S')
NODES=$(tr '\n' ' ' < "$PBS_NODEFILE")
echo "Started $PROG on $DATE"
echo "Using node(s): $NODES"

BN=$(basename "$BAMS" .bam)
Z=${BN%%.*}

mkdir -p "/scratch/$U/${Z}"

cd "/scratch/$U/${Z}" || { echo "ERROR: Failed to set working directory to /scratch/$U/${Z}"; exit 1; }

/home/jocostello/shared/LG3_Pipeline/scripts/Recal_WGS.sh "$BAMS" "$ILIST"

cd "/scratch/$U" || { echo "ERROR: Failed to set working directory to /scratch/$U"; exit 1; }

mkdir -p "/costellolab/data1/jocostello/LG3/exomes_recal/${Z}"
cp -p "/scratch/$U/${Z}"/* "/costellolab/data1/jocostello/LG3/exomes_recal/${PATIENT}" || { echo "ERROR cp!" ; exit 1 ; }
rm -rf "/scratch/$U/${Z}"

echo -n "End of PBS script! "
date
