#!/bin/bash

### Usage: qsub -N Job_Name -v BAMS=/path/to/file1.bam:/path/to/file2.bam:...,NORMAL=AXXXXXX,PATIENT=PatientXX,ILIST=/path/to/exome_kit.interval_list /path/to/Recal_pass2.pbs
### Output files
#PBS -e _Rec2_${PATIENT}.err
#PBS -o _Rec2_${PATIENT}.out
#PBS -l nodes=1:bigmem:ppn=12,vmem=200gb
#PBS -m ae

### Configuration
LG3_HOME=${LG3_HOME:-/home/jocostello/shared/LG3_Pipeline}
LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT:-/costellolab/data1/jocostello}
EMAIL=${EMAIL:?}
PROJECT=${PROJECT:-LG3}
LG3_SCRATCH_ROOT=${LG3_SCRATCH_ROOT:-/scratch/${USER:?}/${PBS_JOBID}}
LG3_DEBUG=${LG3_DEBUG:-true}

### Debug
if [[ $LG3_DEBUG ]]; then
  echo "LG3_HOME=$LG3_HOME"
  echo "LG3_OUTPUT_ROOT=$LG3_OUTPUT_ROOT"
  echo "- PROJECT=${PROJECT}"
  echo "EMAIL=${EMAIL}"
  echo "LG3_SCRATCH_ROOT=$LG3_SCRATCH_ROOT"
  echo "PWD=$PWD"
  echo "USER=$USER"
fi

##### Version of the pipeline without Base Qual. Recal! (for BAMS already recaled!)

date
mkdir -p "${LG3_SCRATCH_ROOT}/${PATIENT}"
cd "${LG3_SCRATCH_ROOT}/${PATIENT}" || { echo "ERROR: Failed to set working directory to ${LG3_SCRATCH_ROOT}/${PATIENT}"; exit 1; }

"${LG3_HOME}/scripts/Recal_pass2.sh" "$BAMS" "$PATIENT" "$ILIST"

cd "${LG3_SCRATCH_ROOT}" || { echo "ERROR: Failed to set working directory to ${LG3_SCRATCH_ROOT}"; exit 1; }

mkdir -p "${LG3_OUTPUT_ROOT}/${PROJECT}/exomes_recal/${PATIENT}"
cp -p "${LG3_SCRATCH_ROOT}/${PATIENT}"/* "${LG3_OUTPUT_ROOT}/${PROJECT}/exomes_recal/${PATIENT}"
rm -rf "${LG3_SCRATCH_ROOT:?}/${PATIENT}"

echo "Making symlinks ..."
cd "${LG3_OUTPUT_ROOT}/${PROJECT}/exomes_recal/${PATIENT}" || { echo "ERROR: failed to cd to ${LG3_OUTPUT_ROOT}/${PROJECT}/exomes_recal/${PATIENT}"; exit 1; }
mk_links() {
  while read -r F
  do
    L=${F/rmDups/rmDups.recal}
    ln -sf "$F" "$L"
  done
}
grep -v recal ./*.bwa.realigned.rmDups.* | mk_links


mkdir -p "${LG3_OUTPUT_ROOT}/${PROJECT}/exomes_recal/${PATIENT}/germline"
cd "${LG3_OUTPUT_ROOT}/${PROJECT}/exomes_recal/${PATIENT}/germline" || { echo "ERROR: Failed to set working directory to ${LG3_OUTPUT_ROOT}/LG3/exomes_recal/${PATIENT}/germline"; exit 1; }

"${LG3_HOME}/scripts/Germline.sh" \
      "${LG3_OUTPUT_ROOT}/${PROJECT}/exomes_recal/${PATIENT}/${NORMAL}.bwa.realigned.rmDups.bam" \
      "${PATIENT}" "$ILIST"

###${LG3_HOME}/resources/All_exome_targets.extended_200bp.interval_list

echo "End of script!"
date
