#!/bin/bash

### Usage: qsub -N Job_Name -v BAMS=/path/to/file1.bam:/path/to/file2.bam:...,NORMAL=AXXXXXX,PATIENT=PatientXX,ILIST=/path/to/exome_kit.interval_list /path/to/Recal.pbs
### Output files
#PBS -e _Recal_${PATIENT}.err
#PBS -o _Recal_${PATIENT}.out
#PBS -l nodes=1:bigmem:ppn=6
#PBS -m ae

### Configuration
LG3_HOME=${LG3_HOME:-/home/jocostello/shared/LG3_Pipeline}
LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT:-/costellolab/data1/jocostello}
SCRATCHDIR=${SCRATCHDIR:-/scratch/${USER:?}}
LG3_DEBUG=${LG3_DEBUG:-true}

### Debug
if [[ $LG3_DEBUG ]]; then
  echo "LG3_HOME=$LG3_HOME"
  echo "LG3_OUTPUT_ROOT=$LG3_OUTPUT_ROOT"
  echo "SCRATCHDIR=$SCRATCHDIR"
  echo "PWD=$PWD"
  echo "USER=$USER"
fi



date
mkdir -p "${SCRATCHDIR}/${PATIENT}"
cd "${SCRATCHDIR}/${PATIENT}" || { echo "ERROR: Failed to set working directory to ${SCRATCHDIR}/${PATIENT}"; exit 1; }

"${LG3_HOME}/scripts/Recal_bigmem.sh" "$BAMS" "$PATIENT" "$ILIST"

cd "${SCRATCHDIR}" || { echo "ERROR: Failed to set working directory to ${SCRATCHDIR}"; exit 1; }
cp -r -p  "${SCRATCHDIR}/${PATIENT}" "${LG3_OUTPUT_ROOT}/LG3/exomes_recal/"
rm "${SCRATCHDIR}/${PATIENT}"

echo -n "End of script! "
date
