#!/bin/bash
### Usage: qsub -N Job_Name -v BAMS=/path/to/file1.bam:/path/to/file2.bam:...,NORMAL=AXXXXXX,PATIENT=PatientXX,ILIST=/path/to/exome_kit.interval_list /path/to/Recal.pbs
#PBS -e _Rec${START}_${PATIENT}.err
#PBS -o _Rec${START}_${PATIENT}.out
#PBS -l nodes=1:ppn=12,vmem=200gb
#PBS -m ae

# shellcheck source=scripts/utils.sh
source "${LG3_HOME:?}/scripts/utils.sh"
source_lg3_conf

PROGRAM=${BASH_SOURCE[0]}
echo "[$(date +'%Y-%m-%d %H:%M:%S %Z')] BEGIN: $PROGRAM"
echo "Call: ${BASH_SOURCE[*]}"
echo "Script: $PROGRAM"
echo "Arguments: $*"

### Configuration
LG3_HOME=${LG3_HOME:?}
LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT:-output}
EMAIL=${EMAIL:?}
PROJECT=${PROJECT:-LG3}
LG3_SCRATCH_ROOT=${LG3_SCRATCH_ROOT:-/scratch/${USER:?}/${PBS_JOBID}}
LG3_DEBUG=${LG3_DEBUG:-true}
START=${START:?}
RECOVER_DIR=${RECOVER_DIR:?}

### Debug
if [[ $LG3_DEBUG ]]; then
  echo "Settings:"
  echo "- LG3_HOME=$LG3_HOME"
  echo "- LG3_OUTPUT_ROOT=$LG3_OUTPUT_ROOT"
  echo "- EMAIL=${EMAIL}"
  echo "- LG3_SCRATCH_ROOT=$LG3_SCRATCH_ROOT"
  echo "- PWD=$PWD"
  echo "- USER=$USER"
  echo "- PBS_NUM_PPN=$PBS_NUM_PPN"
  echo "- hostname=$(hostname)"
fi


### Input
echo "Input:"
echo "- PROJECT=${PROJECT:?}"
echo "- BAMS=${BAMS:?}"
echo "- PATIENT=${PATIENT:?}"
echo "- NORMAL=${NORMAL:?}"
echo "- ILIST=${ILIST:?}"
echo "- START=${START:?}"
echo "- RECOVER_DIR=${RECOVER_DIR:?}"

assert_patient_name "${PATIENT}"

## Assert existance of input files
assert_file_exists "${ILIST}"
ILIST=$(readlink -e "${ILIST:?}") ## Absolute path

echo -n "Checking R: "
"$RSCRIPT" --version || error "No Rscript is available!"

DATE=$(date '+%Y-%m-%d %H:%M:%S')
NODES=$(tr '\n' ' ' < "$PBS_NODEFILE")
echo "Started $PROG on $DATE"
echo "Using node(s): $NODES"

## Assert existance of software
SCRIPT_A=${LG3_HOME}/scripts/Recal_step.sh
SCRIPT_B=${LG3_HOME}/scripts/Germline.sh
assert_file_executable "${SCRIPT_A}"
assert_file_executable "${SCRIPT_B}"

DESTDIR=${LG3_OUTPUT_ROOT}/${PROJECT}/exomes_recal/${PATIENT}
make_dir "${DESTDIR}"

DESTDIR2=${LG3_OUTPUT_ROOT}/${PROJECT}/exomes_recal/${PATIENT}/germline
make_dir "${DESTDIR2}"

WDIR=${LG3_SCRATCH_ROOT}/${PATIENT}
make_dir "${WDIR}"
change_dir "${WDIR}"

echo "Copying recovered data from ${RECOVER_DIR} ..."
cp -p "${RECOVER_DIR}/"* . || error "cp!"

"${SCRIPT_A}" "$BAMS" "$PATIENT" "$ILIST" "$START" "$RECOVER_DIR" || error "${SCRIPT_A} failed"

change_dir "${LG3_SCRATCH_ROOT}"

cp -p "${LG3_SCRATCH_ROOT}/${PATIENT}"/* "${DESTDIR}" || error "cp 1"

echo "Starting germline analysis ..."
WDIR2=${LG3_SCRATCH_ROOT}/${PATIENT}/germline 

make_dir "${WDIR2}"

change_dir "${WDIR2}"

assert_file_exists "../${NORMAL}.bwa.realigned.rmDups.recal.bam"

{ time "${SCRIPT_B}" \
      "../${NORMAL}.bwa.realigned.rmDups.recal.bam" \
      "${PATIENT}" "$ILIST"; } 2>&1 || error "${SCRIPT_B} failed"

cp -p "${LG3_SCRATCH_ROOT}/${PATIENT}"/germline/* "${DESTDIR2}" || error "cp 2" 

echo "Cleaning: rm ${LG3_SCRATCH_ROOT} ..."
rm -rf "${LG3_SCRATCH_ROOT}"

echo "[$(date +'%Y-%m-%d %H:%M:%S %Z')] END: $PROGRAM"
