#!/bin/bash
### Usage: qsub -N Job_Name -v BAMS=/path/to/file1.bam:/path/to/file2.bam:...,NORMAL=AXXXXXX,PATIENT=PatientXX,ILIST=/path/to/exome_kit.interval_list /path/to/Recal.pbs
#PBS -e _Recal_${PATIENT}.err
#PBS -o _Recal_${PATIENT}.out
#PBS -l nodes=1:bigmem:ppn=12,vmem=200gb
#PBS -m ae

PROGRAM=${BASH_SOURCE[0]}
echo "[$(date +'%Y-%m-%d %H:%M:%S %Z')] BEGIN: $PROGRAM"
echo "Call: ${BASH_SOURCE[*]}"
echo "Script: $PROGRAM"
echo "Arguments: $*"

### Configuration
LG3_HOME=${LG3_HOME:-/home/jocostello/shared/LG3_Pipeline}
LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT:-/costellolab/data1/jocostello}
EMAIL=${EMAIL:?}
PROJECT=${PROJECT:-LG3}
SCRATCH_ROOT=${SCRATCH_ROOT:-/scratch/${USER:?}/${PBS_JOBID}}
LG3_DEBUG=${LG3_DEBUG:-true}

### Debug
if [[ $LG3_DEBUG ]]; then
  echo "Settings:"
  echo "- LG3_HOME=$LG3_HOME"
  echo "- LG3_OUTPUT_ROOT=$LG3_OUTPUT_ROOT"
  echo "- EMAIL=${EMAIL}"
  echo "- SCRATCH_ROOT=$SCRATCH_ROOT"
  echo "- PWD=$PWD"
  echo "- USER=$USER"
  echo "- PBS_NUM_PPN=$PBS_NUM_PPN"
fi


### Input
echo "Input:"
echo "- PROJECT=${PROJECT:?}"
echo "- BAMS=${BAMS:?}"
echo "- PATIENT=${PATIENT:?}"
echo "- ILIST=${ILIST:?}"

## Assert existance of input files
[[ -f "$ILIST" ]] || { echo "File not found: ${ILIST}"; exit 1; }
ILIST=$(readlink -e "${ILIST:?}") ## Absolute path


### Updated by Ivan
### New location of recalibrated files and germline analysis output

module load CBC r/3.4.2
Rscript --version

DATE=$(date '+%Y-%m-%d %H:%M:%S')
NODES=$(tr '\n' ' ' < "$PBS_NODEFILE")
echo "Started $PROG on $DATE"
echo "Using node(s): $NODES"

## Assert existance of software
SCRIPT_A=${LG3_HOME}/scripts/Recal_bigmem.sh
[[ -x "$SCRIPT_A" ]] || { echo "File not found or not an executable: ${SCRIPT_A}"; exit 1; }

SCRIPT_B=${LG3_HOME}/scripts/Germline.sh
[[ -x "$SCRIPT_B" ]] || { echo "File not found or not an executable: ${SCRIPT_B}"; exit 1; }

DESTDIR=${LG3_OUTPUT_ROOT}/${PROJECT}/exomes_recal/${PATIENT}
mkdir -p "${DESTDIR}" || { echo "Can't create destination directory ${DESTDIR}"; exit 1; }

DESTDIR2=${LG3_OUTPUT_ROOT}/${PROJECT}/exomes_recal/${PATIENT}/germline
mkdir -p "${DESTDIR2}" || { echo "Can't create destination directory ${DESTDIR2}"; exit 1; }

WDIR=${SCRATCH_ROOT}/${PATIENT}
mkdir -p "${WDIR}" || { echo "Can't create destination directory ${WDIR}"; exit 1; }
cd "${WDIR}" || { echo "ERROR: Failed to set working directory to ${WDIR}"; exit 1; }

"${SCRIPT_A}" "$BAMS" "$PATIENT" "$ILIST"

cd "${SCRATCH_ROOT}" || { echo "ERROR: Failed to set working directory to ${SCRATCH_ROOT}"; exit 1; }

cp -p "${SCRATCH_ROOT}/${PATIENT}"/* "${DESTDIR}" || { echo "ERROR cp!" ; exit 1 ; }

echo "Cleaning ${SCRATCH_ROOT} ..."
rm -rf "${SCRATCH_ROOT:?}/${PATIENT}"

cd "${DESTDIR2}" || { echo "ERROR: Failed to set working directory to ${DESTDIR2}"; exit 1; }

"${SCRIPT_B}" \
      "${LG3_OUTPUT_ROOT}/${PROJECT}/exomes_recal/${PATIENT}/${NORMAL}.bwa.realigned.rmDups.recal.bam" \
      "${PATIENT}" "$ILIST"

echo -n "End of script! "
date

echo "[$(date +'%Y-%m-%d %H:%M:%S %Z')] END: $PROGRAM"
