#!/bin/bash
LG3_HOME=${LG3_HOME:-/home/jocostello/shared/LG3_Pipeline}
CONV=${CONV:-patient_ID_conversions.txt}
PATIENT=${PATIENT:-Patient157t}

"${LG3_HOME}/scripts/chk_data.sh" \
	-fastq=true \
	-trim=true \
	-bwa=true \
	-recal=true \
	-germline=true \
	-pindel=true \
	-mutect=true \
	-combined=true \
	-conv=$CONV \
	${PATIENT}
