#!/bin/bash

### Output files
#PBS -e _UG_${PAT}.err
#PBS -o _UG_${PAT}.out
#PBS -l nodes=1:bigmem:ppn=12
#PBS -m ae
NODES=$(cat "$PBS_NODEFILE" | tr '\n' ' ')

DATE=$(date '+%Y-%m-%d %H:%M:%S')
echo "Started $PROG on $DATE"
echo "Using node(s): $NODES"
echo "BAMS=$BAMS"
echo "OUT=$OUT"

/home/jocostello/shared/LG3_Pipeline/scripts/UG.sh \
      -bams="$BAMS" \
      -out="${OUT}" \
      -list="$ILIST"

echo -n "End of script! "
date
