#!/bin/bash

# shellcheck source=scripts/utils.sh
source "${LG3_HOME}/scripts/utils.sh"

PROGRAM=${BASH_SOURCE[0]}
echo "[$(date +'%Y-%m-%d %H:%M:%S %Z')] BEGIN: $PROGRAM"
echo "Call: ${BASH_SOURCE[*]}"
echo "Script: $PROGRAM"
echo "Arguments: $*"

# shellcheck source=scripts/config_run.sh
source "${LG3_HOME}/scripts/config_run.sh"

## Requires absolute path 
LG3_HOME=$(readlink -e "$LG3_HOME")
LG3_OUTPUT_ROOT=$(readlink -e "$LG3_OUTPUT_ROOT")

echo "Input:"
echo "- LG3_HOME=${LG3_HOME:?}"
echo "- LG3_INPUT_ROOT=${LG3_INPUT_ROOT:?}"
echo "- LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT:?}"
echo "- EMAIL=${EMAIL}"
echo "- PATIENT=${PATIENT:?}"
echo "- PROJECT=${PROJECT:?}"
echo "- CONV=${CONV:?}"

assert_patient_name "${PATIENT}"

assert_file_exists "${CONV}"
CONV=$(readlink -e "$CONV")

SH_MUTDET_SUBMIT=${LG3_HOME}/scripts/mutdet_submit.sh
assert_file_executable "${SH_MUTDET_SUBMIT}"

echo -n "Submitting jobs for $PATIENT "
date

## Assert that input files exist
D=${LG3_OUTPUT_ROOT}/${PROJECT}/exomes_recal/${PATIENT}
assert_directory_exists "${D}"

## Pass QSUB_OPTS to ${SH_MUTDET_SUBMIT} where it's an optional input
export QSUB_OPTS

"${SH_MUTDET_SUBMIT}" "${PATIENT}" "${CONV}" "${PROJECT}" || error "${SH_MUTDET_SUBMIT} failed"

echo "[$(date +'%Y-%m-%d %H:%M:%S %Z')] END: $PROGRAM"
