#!/bin/bash

LG3_HOME=${LG3_HOME:-/home/jocostello/shared/LG3_Pipeline}
LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT:-/costellolab/data1/jocostello}
EMAIL=${EMAIL:-ivan.smirnov@ucsf.edu}

echo "LG3_HOME=${LG3_HOME}"
echo "LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT}"
echo "EMAIL=${EMAIL}"

QSUB_OPTS="-d ${PWD:?} -v LG3_HOME=${LG3_HOME},LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT},EMAIL=${EMAIL}"

## Override the qsub email address?
if [[ -n ${EMAIL} ]]; then
  QSUB_OPTS="${QSUB_OPTS} -M ${EMAIL}"
fi

echo "QSUB_OPTS=${QSUB_OPTS}"

## Location of output: aligned BAMs
ALIGN=${LG3_OUTPUT_DIR}/exomes

for N in 599 600 601
do
	Z=Z00${N}
	FQ1=rawdata/${Z}-trim/${Z}-trim_R1.fastq.gz
	FQ2=rawdata/${Z}-trim/${Z}-trim_R2.fastq.gz

	if [ ! -r $FQ1 ] || [ ! -r $FQ2 ]; then
		echo "ERROR: Can't open $Z from rawdata/"
	else
		if [ -f "${ALIGN}/${Z}.trim.bwa.sorted.bam" ]; then
			echo "WARNING: already aligned: $ALIGN/${Z}.trim.bwa.sorted.bam"
			echo "Skipping $Z ..."
		else
		        echo "Submitting $Z ..."
		        # shellcheck disable=SC2086
			qsub ${QSUB_OPTS} -N Align_$Z -v FASTQ1=$FQ1,FASTQ2=$FQ2,PREFIX=$Z "${LG3_HOME}/Align_fastq.pbs"
		fi
	fi
done
