#!/bin/bash
### Time 8h , 6 CPUs , vmem >= 2GB

LG3_HOME=${LG3_HOME:-/home/jocostello/shared/LG3_Pipeline}
LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT:-/costellolab/data1/jocostello}
EMAIL=${EMAIL:-ivan.smirnov@ucsf.edu}

echo "LG3_HOME=${LG3_HOME}"
echo "LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT}"
echo "EMAIL=${EMAIL}"

QSUB_OPTS=-d $(pwd)

## Override the qsub email address?
if [[ -n ${EMAIL} ]]; then
  QSUB_OPTS="${QSUB_OPTS} -M ${EMAIL}"
fi

PATIENT=Patient157
PROJ=LG3

CONV=patient_ID_conversions.txt
PBS=${LG3_HOME}/pindel_all.pbs

# shellcheck disable=SC2086
qsub ${QSUB_OPTS} -N ${PATIENT}.pindel -v SAMPLE=$PATIENT,PROJ=$PROJ,CONV=$CONV "$PBS"

