#!/bin/bash
### Time 8h , 6 CPUs , vmem >= 2GB

LG3_HOME=${LG3_HOME:-/home/jocostello/shared/LG3_Pipeline}
EMAIL=${EMAIL:-ivan.smirnov@ucsf.edu}

PATIENT=Patient157
PROJ=LG3

CONV=patient_ID_conversions.txt
PBS=${LG3_HOME}/pindel_all.pbs

qsub -N ${PATIENT}.pindel -M "${EMAIL}" -v SAMPLE=$PATIENT,PROJ=$PROJ,CONV=$CONV "$PBS"

