#!/bin/bash

# shellcheck source=scripts/utils.sh
source "${LG3_HOME:?}/scripts/utils.sh"
source_lg3_conf

assert_pwd

PROGRAM=${BASH_SOURCE[0]}
echo "[$(date +'%Y-%m-%d %H:%M:%S %Z')] BEGIN: $PROGRAM"
echo "Call: ${BASH_SOURCE[*]}"
echo "Script: $PROGRAM"
echo "Arguments: $*"

LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT:-output}
LG3_INPUT_ROOT=${LG3_INPUT_ROOT:-${LG3_OUTPUT_ROOT}}
EMAIL=${EMAIL:?}
PATIENT=${PATIENT:-Patient157t10}
MUTATIONFILE=${LG3_INPUT_ROOT}/${PROJECT}/MutInDel/${PATIENT}.snvs.indels.filtered.overlaps.txt
BAMPATH=${LG3_INPUT_ROOT}/${PROJECT}/exomes_recal
WORKDIR=${LG3_OUTPUT_ROOT}/${PROJECT}/exome_QC_plots/${PATIENT}

if [ ! -r "${QC_PLOT_HOME}" ]; then
	error "QC_PLOT_HOME link is not set! Please clone 'exomeQualityPlots' repo and provide link"
fi

## Requires absolute path
LG3_OUTPUT_ROOT=$(readlink -e "${LG3_OUTPUT_ROOT}")

echo "Input: "
echo "- LG3_HOME=${LG3_HOME:?}"
echo "- LG3_INPUT_ROOT=${LG3_INPUT_ROOT}"
echo "- LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT:?}"
echo "- QC_PLOT_HOME=${QC_PLOT_HOME}"
echo "- PROJECT=${PROJECT:?}"
echo "- PATIENT=${PATIENT:?}"
echo "- EMAIL=${EMAIL}"

## Assert that the conversion file exists
assert_file_exists "${CONV}"
echo "- CONV=${CONV}"

## Assert that the mutation file exists
assert_file_exists "${MUTATIONFILE}"
MUTATIONFILE=$(readlink -e "${MUTATIONFILE}")
echo "- MUTATIONFILE=${MUTATIONFILE}"

assert_directory_exists "${BAMPATH}"
BAMPATH=$(readlink -e "${BAMPATH}") ## requires absolute path
echo "- BAMPATH=${BAMPATH}"

make_dir "${WORKDIR}"
WORKDIR=$(readlink -e "${WORKDIR}")
change_dir "${WORKDIR}"
echo "- WORKDIR=${WORKDIR}"

ls -1 "${BAMPATH}/${PATIENT}/"*."${RECAL_BAM_EXT}.bam" || error "No bam files found in ${BAMPATH}"

PBS=${QC_PLOT_HOME}/annotate_mutations_from_bam_vSH.sh
assert_file_executable "${PBS}"

PN=${PATIENT/Patient/Pat}
qsub -l vmem=96gb -e "_QC1_${PATIENT}.err" -o "_QC1_${PATIENT}.out" -N "QC1_${PN}" -M "${EMAIL}" -m ae -v "mutationfile=${MUTATIONFILE},conversionfile=${CONV},patient=${PATIENT},project=${PROJECT},bampath=${BAMPATH},scriptpath=${QC_PLOT_HOME},RECAL_BAM_EXT=${RECAL_BAM_EXT}" "${PBS}"

echo "[$(date +'%Y-%m-%d %H:%M:%S %Z')] END: $PROGRAM"
