#!/bin/bash

# shellcheck disable=SC1072,SC1073
source "${LG3_HOME:?}/scripts/utils.sh"
source_lg3_conf

assert_pwd

echo "ETA ~4h"

PROGRAM=${BASH_SOURCE[0]}
echo "[$(date +'%Y-%m-%d %H:%M:%S %Z')] BEGIN: $PROGRAM"
echo "Call: ${BASH_SOURCE[*]}"
echo "Script: $PROGRAM"
echo "Arguments: $*"

LG3_HOME=${LG3_HOME:?}
LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT:-output}
LG3_INPUT_ROOT=${LG3_INPUT_ROOT:-rawdata}
PROJECT=${PROJECT:-LG3}
PATIENT=${PATIENT:-Patient157t10}
CONV=${CONV:-patient_ID_conversions.tsv}
SAMPLES=${SAMPLES:-$(grep -P "\\t${PATIENT}\\t" "${CONV}" | cut -f1 | tr '\n' ' ')}

## Requires absolute path 
LG3_HOME=$(readlink -e "$LG3_HOME")
LG3_OUTPUT_ROOT=$(readlink -e "$LG3_OUTPUT_ROOT")
LG3_DEBUG=false

echo "Input:"
echo "- LG3_HOME=${LG3_HOME:?}"
echo "- PROJECT=${PROJECT:?}"
echo "- PATIENT=${PATIENT:?}"
echo "- CONV=${CONV:?}"
echo "- SAMPLES=${SAMPLES:?}"
echo "- LG3_INPUT_ROOT=${LG3_INPUT_ROOT:?}"
echo "- LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT:?}"
echo "- EMAIL=${EMAIL:?}"
echo "- LG3_DEBUG=${LG3_DEBUG:?}"

assert_patient_name "${PATIENT}"

PBS=${LG3_HOME}/trim_galore.pbs
assert_file_exists "${PBS}"

QTY=20

for SAMPLE in ${SAMPLES}; do
    ## Use file globbing to allow for optional suffixes after _R1 and _R2.
    ## FIXME: shopt -s nullglob  ## Return empty array if no matches are found
    FASTQ1s=("${LG3_INPUT_ROOT}/${SAMPLE}_R1"*.fastq.gz)
    FASTQ2s=("${LG3_INPUT_ROOT}/${SAMPLE}_R2"*.fastq.gz)

    ## Assert that at most single files were found by globbing
    [[ ${#FASTQ1s[@]} -eq 1 ]] || error "Expected one file: [${#FASTQ1s[@]}] ${FASTQ1s[*]}"
    [[ ${#FASTQ2s[@]} -eq 1 ]] || error "Expected one file: [${#FASTQ2s[@]}] ${FASTQ2s[*]}"

    ## Requires absolute path 
    FASTQ1=$(readlink -e "${FASTQ1s[0]}")
    FASTQ2=$(readlink -e "${FASTQ2s[0]}")
   
    [[ -r "${FASTQ1}" ]] || error "Can't open $SAMPLE from ${LG3_INPUT_ROOT}/: ${FASTQ1}"
    [[ -r "${FASTQ2}" ]] || error "Can't open $SAMPLE from ${LG3_INPUT_ROOT}/: ${FASTQ2}"

    echo "Submitting $SAMPLE: quality $QTY ..."
    echo "- FASTQ1: ${FASTQ1}"
    echo "- FASTQ2: ${FASTQ2}"
    
	sbatch --mail-user="${EMAIL}" --mail-type=END,FAIL \
	   --job-name="Tr-${SAMPLE}" \
     	--output="Trim-${SAMPLE}.out" \
     	--error="Trim-${SAMPLE}.err" \
		--export=ALL,LG3_HOME="${LG3_HOME}",LG3_OUTPUT_ROOT="${LG3_OUTPUT_ROOT}",SAMPLE="${SAMPLE}",FASTQ1="${FASTQ1}",FASTQ2="${FASTQ2}",QTY="${QTY}",PROJECT="${PROJECT}",LG3_DEBUG="${LG3_DEBUG}" \
      --nodes=1 \
      --ntasks=2 \
      --mem=8G \
      --time=1-06:00:00 \
		"${PBS}"
done

echo "[$(date +'%Y-%m-%d %H:%M:%S %Z')] END: $PROGRAM"
