#!/bin/bash

LG3_HOME=${LG3_HOME:-/home/jocostello/shared/LG3_Pipeline}
LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT:-/costellolab/data1/jocostello}
EMAIL=${EMAIL:-ivan.smirnov@ucsf.edu}

echo "LG3_HOME=${LG3_HOME}"
echo "LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT}"
echo "EMAIL=${EMAIL}"

QSUB_OPTS="-d ${PWD:?} -v LG3_HOME=${LG3_HOME},LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT},EMAIL=${EMAIL}"

## Override the qsub email address?
if [[ -n ${EMAIL} ]]; then
  QSUB_OPTS="${QSUB_OPTS} -M ${EMAIL}"
fi

echo "QSUB_OPTS=${QSUB_OPTS}"

PATIENT=Patient157
PROJ=LG3

CONV=patient_ID_conversions.txt
PBS=${LG3_HOME}/post_mutect_pindel.pbs

"${LG3_HOME}/scripts/chk_pindel.sh" $PATIENT
"${LG3_HOME}/scripts/chk_mutdet.sh" $PATIENT

# shellcheck disable=SC2086
qsub ${QSUB_OPTS} -N ${PATIENT}_comb -v PATIENT=$PATIENT,PROJ=$PROJ,CONV=$CONV "$PBS"
