#!/bin/bash

# shellcheck source=scripts/utils.sh
source "${LG3_HOME}/scripts/utils.sh"

PROGRAM=${BASH_SOURCE[0]}
echo "[$(date +'%Y-%m-%d %H:%M:%S %Z')] BEGIN: $PROGRAM"
echo "Call: ${BASH_SOURCE[*]}"
echo "Script: $PROGRAM"
echo "Arguments: $*"

# shellcheck source=scripts/config_run.sh
source "${LG3_HOME}/scripts/config_run.sh"

SAMPLES=${SAMPLES:-Z00600t10 Z00601t10}
SAMPLE=${SAMPLE:-Y00600t10}

## Requires absolute path
LG3_HOME=$(readlink -e "$LG3_HOME")
LG3_OUTPUT_ROOT=$(readlink -e "$LG3_OUTPUT_ROOT")

echo "Input:"
echo "- LG3_HOME=${LG3_HOME:?}"
echo "- LG3_INPUT_ROOT=${LG3_INPUT_ROOT:?}"
echo "- LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT:?}"
echo "- EMAIL=${EMAIL}"
echo "- PROJECT=${PROJECT:?}"
echo "- PATIENT=${PATIENT:?}"
echo "- SAMPLES=${SAMPLES:?}"
echo "- SAMPLE=${SAMPLE:?}"

assert_patient_name "${PATIENT}"

QSUB_ENVVARS="LG3_HOME=${LG3_HOME},LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT},PROJECT=${PROJECT},EMAIL=${EMAIL}"
QSUB_OPTS="${QSUB_OPTS} -d ${PWD:?}"

## Override the qsub email address?
if [[ -n ${EMAIL} ]]; then
  QSUB_OPTS="${QSUB_OPTS} -M ${EMAIL}"
fi

echo "Qsub extras:"
echo "- QSUB_OPTS=${QSUB_OPTS}"
echo "- QSUB_ENVVARS=${QSUB_ENVVARS}"

PBS=${LG3_HOME}/Merge.pbs
assert_file_exists "${PBS}"

D=${LG3_INPUT_ROOT}/${PROJECT}/exomes_recal
assert_directory_exists "${D}"
D=$(readlink -e "$D") ## requires absolute path

SUFF=bwa.realigned.rmDups.recal.bam

CNT=0
for S in ${SAMPLES}
do
   ((CNT++))
   B=$D/${PATIENT}/${S}.$SUFF
   assert_file_exists "${B}"
   echo "Found $B"
   BAMS=${BAMS}:$B
done
## Clip first char (:)
BAMS=$(echo "$BAMS" | cut -c2-)
echo "Total BAMS: $CNT"
echo "$BAMS"

# shellcheck disable=SC2086
qsub ${QSUB_OPTS} -N Merge_${SAMPLE} -v "${QSUB_ENVVARS},BAMS=${BAMS},SAMPLE=${SAMPLE},PATIENT=${PATIENT}" "$PBS"
