#!/bin/bash
### Time 8h , 6 CPUs , vmem >= 2GB

# shellcheck source=scripts/utils.sh
source "${LG3_HOME}/scripts/utils.sh"

PROGRAM=${BASH_SOURCE[0]}
echo "[$(date +'%Y-%m-%d %H:%M:%S %Z')] BEGIN: $PROGRAM"
echo "Call: ${BASH_SOURCE[*]}"
echo "Script: $PROGRAM"
echo "Arguments: $*"

LG3_HOME=${LG3_HOME:?}
LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT:-output}
LG3_INPUT_ROOT=${LG3_INPUT_ROOT:-${LG3_OUTPUT_ROOT}}
PROJECT=${PROJECT:-LG3}
CONV=${CONV:-patient_ID_conversions.tsv}
PATIENT=${PATIENT:-Patient157t10}
EMAIL=${EMAIL:?}

## Requires absolute path 
LG3_HOME=$(readlink -e "$LG3_HOME")
LG3_OUTPUT_ROOT=$(readlink -e "$LG3_OUTPUT_ROOT")

echo "Input:"
echo "- LG3_HOME=${LG3_HOME:?}"
echo "- LG3_INPUT_ROOT=${LG3_INPUT_ROOT:?}"
echo "- LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT:?}"
echo "- EMAIL=${EMAIL}"
echo "- PATIENT=${PATIENT:?}"
echo "- PROJECT=${PROJECT:?}"
echo "- CONV=${CONV:?}"

assert_patient_name "${PATIENT}"

QSUB_ENVVARS="LG3_HOME=${LG3_HOME},LG3_INPUT_ROOT=${LG3_INPUT_ROOT},LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT},EMAIL=${EMAIL}"
QSUB_OPTS="${QSUB_OPTS} -d ${PWD:?}"

## Override the qsub email address?
if [[ -n ${EMAIL} ]]; then
  QSUB_OPTS="${QSUB_OPTS} -M ${EMAIL}"
fi

echo "Qsub extras:"
echo "- QSUB_OPTS=${QSUB_OPTS}"
echo "- QSUB_ENVVARS=${QSUB_ENVVARS}"

assert_file_exists "${CONV}"
CONV=$(readlink -e "$CONV")

PBS=${LG3_HOME}/pindel_all.pbs
assert_file_exists "${PBS}"

## Assert that input directory exist
D=${LG3_OUTPUT_ROOT}/${PROJECT}/exomes_recal/${PATIENT}
assert_directory_exists "${D}"

# shellcheck disable=SC2086
qsub ${QSUB_OPTS} -N ${PATIENT}.pindel -v "${QSUB_ENVVARS},PATIENT=${PATIENT},PROJECT=${PROJECT},CONV=${CONV}" "$PBS"

echo "[$(date +'%Y-%m-%d %H:%M:%S %Z')] END: $PROGRAM"
