#!/bin/bash

# shellcheck source=scripts/utils.sh
source "${LG3_HOME:?}/scripts/utils.sh"
source_lg3_conf

PROGRAM=${BASH_SOURCE[0]}
echo "[$(date +'%Y-%m-%d %H:%M:%S %Z')] BEGIN: $PROGRAM"
echo "Call: ${BASH_SOURCE[*]}"
echo "Script: $PROGRAM"
echo "Arguments: $*"

LG3_HOME=${LG3_HOME:?}
LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT:-output}
LG3_INPUT_ROOT=${LG3_INPUT_ROOT:-rawdata}
#LG3_INPUT_ROOT=${LG3_INPUT_ROOT:-${LG3_OUTPUT_ROOT}}
PROJECT=${PROJECT:-LG3}
PATIENT=${PATIENT:-Patient157t10}
CONV=${CONV:-patient_ID_conversions.tsv}
LG3_CHASTITY_FILTERING=${LG3_CHASTITY_FILTERING:-false}
EMAIL=${EMAIL:?}

## Requires absolute path 
LG3_HOME=$(readlink -e "$LG3_HOME")
LG3_OUTPUT_ROOT=$(readlink -e "$LG3_OUTPUT_ROOT")

echo "Input:"
echo "- LG3_HOME=${LG3_HOME:?}"
echo "- LG3_INPUT_ROOT=${LG3_INPUT_ROOT:?}"
#echo "- LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT:?}"
echo "- EMAIL=${EMAIL}"
echo "- PROJECT=${PROJECT:?}"
echo "- PATIENT=${PATIENT:?}"
echo "- CONV=${CONV:?}"
echo "- INTERVAL=${INTERVAL:?}"
echo "- PADDING=${PADDING:?}"
echo "- LG3_CHASTITY_FILTERING=${LG3_CHASTITY_FILTERING}"

assert_patient_name "${PATIENT}"

SAMPLES=${SAMPLES:-$(grep -P "\\t${PATIENT}\\t" "${CONV}" | cut -f1 | tr '\n' ' ')}
echo "- SAMPLES=${SAMPLES:?}"


QSUB_ENVVARS="LG3_HOME=${LG3_HOME},LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT},EMAIL=${EMAIL}"
QSUB_OPTS="${QSUB_OPTS} -d ${PWD:?}"

## Override the qsub email address?
if [[ -n ${EMAIL} ]]; then
  QSUB_OPTS="${QSUB_OPTS} -M ${EMAIL}"
fi

echo "Qsub extras:"
echo "- QSUB_OPTS=${QSUB_OPTS}"
echo "- QSUB_ENVVARS=${QSUB_ENVVARS}"

PBS=${LG3_HOME}/Align_mem.pbs
assert_file_exists "${PBS}"


for SAMPLE in ${SAMPLES}
do
  FASTQ1=${LG3_INPUT_ROOT}/${SAMPLE}_R1.fastq.gz
  FASTQ2=${LG3_INPUT_ROOT}/${SAMPLE}_R2.fastq.gz

  ## Requires absolute path 
  FASTQ1=$(readlink -e "$FASTQ1")
  FASTQ2=$(readlink -e "$FASTQ2")
  
  ## Expected Location of prepared BAMs
  ALIGNED=${LG3_OUTPUT_ROOT}/${PROJECT}/exomes_recal/${PATIENT}

  if [ ! -r "${FASTQ1}" ] || [ ! -r "${FASTQ2}" ]; then
    warn "Can't open FastQ file for $SAMPLE from ${LG3_INPUT_ROOT}/"
  else
    if [ -f "${ALIGNED}/${SAMPLE}.*.recal.bam" ]; then
      warn "${SAMPLE} is aligned (${ALIGNED}/${SAMPLE}.*.recal.bam). Skipping ..."
    else
      echo "Submitting $SAMPLE ..."
      # shellcheck disable=SC2086
      qsub ${QSUB_OPTS} -N Align_$SAMPLE -v "${QSUB_ENVVARS},FASTQ1=${FASTQ1},FASTQ2=${FASTQ2},SAMPLE=${SAMPLE},PATIENT=${PATIENT},LG3_CHASTITY_FILTERING=${LG3_CHASTITY_FILTERING},PROJECT=${PROJECT}" "${PBS}"
    fi
  fi
done

echo "[$(date +'%Y-%m-%d %H:%M:%S %Z')] END: $PROGRAM"
