#!/bin/bash

LG3_HOME=${LG3_HOME:-/home/jocostello/shared/LG3_Pipeline}
LG3_OUTPUT_DIR=${LG3_OUTPUT_DIR:-/costellolab/data1/jocostello/LG3}
EMAIL=${EMAIL:-ivan.smirnov@ucsf.edu}

ILIST=resources/SeqCap_EZ_Exome_v3_capture.interval_list
PBS=${LG3_HOME}/Recal_bigmem.pbs

D=${LG3_OUTPUT_DIR}/exomes

PATIENT=Patient157
NORMAL=Z00599
SUFF=trim.bwa.sorted.bam

CNT=0
for N in $(seq 599 601)
do
	((CNT++))
	B=$D/Z00$N/Z00$N.$SUFF
 	if [ ! -f "$B" ]; then
      echo "ABORT: Can't open $B !"
      exit 1
   fi
   echo "Found $B"
   BAMS=${BAMS}:$B
done
## Clip first char (:)
BAMS=$(echo "$BAMS" | cut -c2-)
echo "Total BAMS: $CNT"
echo "$BAMS"

qsub -N Recal_$PATIENT -v "BAMS=$BAMS,NORMAL=$NORMAL,PATIENT=$PATIENT,ILIST=$ILIST" "$PBS"
