#!/bin/bash

PROGRAM=${BASH_SOURCE[0]}
echo "[$(date +'%Y-%m-%d %H:%M:%S %Z')] BEGIN: $PROGRAM"
echo "Call: ${BASH_SOURCE[*]}"
echo "Script: $PROGRAM"
echo "Arguments: $*"

LG3_HOME=${LG3_HOME:-/home/jocostello/shared/LG3_Pipeline}
LG3_INPUT_ROOT=${LG3_INPUT_ROOT:-/costellolab/data1/jocostello}
LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT:-output}
PROJECT=${PROJECT:-LG3}
EMAIL=${EMAIL:?}
SAMPLES=${SAMPLES:-Z00599t Y00600t}
NORMAL=${NORMAL:-Z00599t}
PATIENT=${PATIENT:-Patient157t}
ILIST=${ILIST:-resources/SeqCap_EZ_Exome_v3_capture.interval_list}

## Requires absolute path 
LG3_HOME=$(readlink -e "$LG3_HOME")
LG3_OUTPUT_ROOT=$(readlink -e "$LG3_OUTPUT_ROOT")

echo "Input:"
echo "- LG3_HOME=${LG3_HOME:?}"
echo "- LG3_INPUT_ROOT=${LG3_INPUT_ROOT:?}"
echo "- LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT:?}"
echo "- EMAIL=${EMAIL}"
echo "- SAMPLES=${SAMPLES:?}"
echo "- NORMAL=${NORMAL:?}"
echo "- PATIENT=${PATIENT:?}"
echo "- ILIST=${ILIST:?}"

[[ -f "$ILIST" ]] || { echo "File not found: ${ILIST}"; exit 1; }
ILIST=$(readlink -e "$ILIST")

## Assert that NORMAL is one of the SAMPLES
echo "${SAMPLES}" | grep -q -P "(^|\\t| )${NORMAL}(\\t| |$)" || { echo "ERROR: NORMAL '${NORMAL}' is not part of SAMPLES: ${SAMPLES}"; exit 1; }


QSUB_ENVVARS="LG3_HOME=${LG3_HOME},LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT},EMAIL=${EMAIL},PROJECT=${PROJECT}"
QSUB_OPTS="${QSUB_OPTS} -d ${PWD:?}"

## Override the qsub email address?
if [[ -n ${EMAIL} ]]; then
  QSUB_OPTS="${QSUB_OPTS} -M ${EMAIL}"
fi

echo "Qsub extras:"
echo "- QSUB_OPTS=${QSUB_OPTS}"
echo "- QSUB_ENVVARS=${QSUB_ENVVARS}"

PBS=${LG3_HOME}/Recal_pass2.pbs
[[ -f "$PBS" ]] || { echo "File not found: ${PBS}"; exit 1; }

D=${LG3_INPUT_ROOT}/${PROJECT}/exomes_recal
[[ -d "$D" ]] || { echo "Directory not found: ${D}"; exit 1; }
D=$(readlink -e "$D") ## requires absolute path

[[ -d "$D/${PATIENT}" ]] || { echo "Directory not found: ${D}/${PATIENT}"; exit 1; }

echo "Renaming $D/${PATIENT} to $D/${PATIENT}.before.merge"
mv "$D/${PATIENT}" "$D/${PATIENT}.before.merge"

SUFF=bwa.realigned.rmDups.recal.bam

CNT=0
for PREFIX in ${SAMPLES}
do
   ((CNT++))
   B=$D/${PATIENT}.before.merge/${PREFIX}.$SUFF
   if [ ! -f "$B" ]; then
      echo "ABORT: Can't open $B !"
      exit 1
   fi
   echo "Found $B"
   BAMS=${BAMS}:$B
done
## Clip first char (:)
BAMS=$(echo "$BAMS" | cut -c2-)
echo "Total BAMS: $CNT"
echo "$BAMS"

# shellcheck disable=SC2086
qsub ${QSUB_OPTS} -N Rec2_$PATIENT -v "${QSUB_ENVVARS},BAMS=${BAMS},NORMAL=${NORMAL},PATIENT=${PATIENT},ILIST=${ILIST}" "$PBS"

echo "[$(date +'%Y-%m-%d %H:%M:%S %Z')] END: $PROGRAM"
