#!/bin/bash

LG3_HOME=${LG3_HOME:-/home/jocostello/shared/LG3_Pipeline}
LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT:-/costellolab/data1/jocostello}
EMAIL=${EMAIL:-ivan.smirnov@ucsf.edu}

echo "LG3_HOME=${LG3_HOME}"
echo "LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT}"
echo "EMAIL=${EMAIL}"

QSUB_OPTS="-d ${PWD:?} -v LG3_HOME=${LG3_HOME},LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT},EMAIL=${EMAIL}"

## Override the qsub email address?
if [[ -n ${EMAIL} ]]; then
  QSUB_OPTS="${QSUB_OPTS} -M ${EMAIL}"
fi

echo "QSUB_OPTS=${QSUB_OPTS}"

PBS=${LG3_HOME}/trim_galore.pbs

echo "ETA ~4h"

QTY=20

for N in 599 600 601
do
   Z=Z00${N}
   if [ ! -r rawdata/${Z}_R1.fastq.gz ] || [ ! -r rawdata/${Z}_R1.fastq.gz ]; then
      echo "ERROR: Can't open $Z from rawdata/"
   else
      echo "Submitting $Z: quality $QTY ..."
      # shellcheck disable=SC2086
      qsub ${QSUB_OPTS} -N trim${QTY}_$Z -v FASTQ1=rawdata/${Z}_R1.fastq.gz,FASTQ2=rawdata/${Z}_R2.fastq.gz,PREFIX=$Z,QTY=$QTY "$PBS"
   fi
done
