#!/bin/bash

PATIENT=Patient450
PROJ=LG3

CONV=/costellolab/mazort/LG3/exome/patient_ID_conversions.txt

echo -n "Submitting jobs for $PATIENT "
date
/home/jocostello/shared/LG3_Pipeline/scripts/mutdet_submit.sh $PATIENT $CONV $PROJ
