#!/bin/bash

LG3_HOME=${LG3_HOME:-/home/jocostello/shared/LG3_Pipeline}
LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT:-/costellolab/data1/jocostello}
EMAIL=${EMAIL:-ivan.smirnov@ucsf.edu}

## Requires absolute path 
LG3_HOME=$(readlink -e "$LG3_HOME")
LG3_OUTPUT_ROOT=$(readlink -e "$LG3_OUTPUT_ROOT")

echo "LG3_HOME=${LG3_HOME}"
echo "LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT}"
echo "EMAIL=${EMAIL}"

QSUB_ENVVARS="LG3_HOME=${LG3_HOME},LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT},EMAIL=${EMAIL}"
QSUB_OPTS="-d ${PWD:?}"

## Override the qsub email address?
if [[ -n ${EMAIL} ]]; then
  QSUB_OPTS="${QSUB_OPTS} -M ${EMAIL}"
fi

echo "QSUB_OPTS=${QSUB_OPTS}"

ILIST=resources/SeqCap_EZ_Exome_v3_capture.interval_list

PBS=${LG3_HOME}/Recal_bigmem.pbs

D=${LG3_OUTPUT_DIR}/exomes

## Requires absolute path 
#TODO# D=$(readlink -e "$D")
#TODO# ILIST=$(readlink -e "$ILIST")

PATIENT=Patient157
NORMAL=Z00599
SUFF=trim.bwa.sorted.bam

CNT=0
for N in $(seq 599 601)
do
	((CNT++))
	B=$D/Z00$N/Z00$N.$SUFF
 	if [ ! -f "$B" ]; then
      echo "ABORT: Can't open $B !"
      exit 1
   fi
   echo "Found $B"
   BAMS=${BAMS}:$B
done
## Clip first char (:)
BAMS=$(echo "$BAMS" | cut -c2-)
echo "Total BAMS: $CNT"
echo "$BAMS"

# shellcheck disable=SC2086
qsub ${QSUB_OPTS} -N Recal_$PATIENT -v "${QSUB_ENVVARS},BAMS=${BAMS},NORMAL=${NORMAL},PATIENT=${PATIENT},ILIST=${ILIST}" "$PBS"
