#!/bin/bash

# shellcheck source=scripts/utils.sh
source "${LG3_HOME:?}/scripts/utils.sh"
source_lg3_conf

assert_pwd

PROGRAM=${BASH_SOURCE[0]}
echo "[$(date +'%Y-%m-%d %H:%M:%S %Z')] BEGIN: $PROGRAM"
echo "Call: ${BASH_SOURCE[*]}"
echo "Script: $PROGRAM"
echo "Arguments: $*"

LG3_HOME=${LG3_HOME:?}
LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT:-output}
LG3_INPUT_ROOT=${LG3_INPUT_ROOT:-${LG3_OUTPUT_ROOT}}
#QC_PLOT_HOME=${QC_PLOT_HOME:-exomeQualityPlots}
EMAIL=${EMAIL:?}
PROJECT=${PROJECT:-LG3}
PATIENT=${PATIENT:-Patient157t10}
#BEDPATH=${BEDPATH:-${LG3_HOME}/resources/SeqCap_EZ_Exome_v3_capture.bed}
BEDPATH=${BEDPATH:-${LG3_HOME}/resources/xgen-exome-research-panel-targets_6bpexpanded.bed}
BAMPATH=${LG3_INPUT_ROOT}/${PROJECT}/exomes_recal
WORKDIR=${LG3_OUTPUT_ROOT}/${PROJECT}/exome_QC_plots/${PATIENT}

## Requires absolute path
LG3_HOME=$(readlink -e "$LG3_HOME")
LG3_OUTPUT_ROOT=$(readlink -e "$LG3_OUTPUT_ROOT")
QC_PLOT_HOME=${LG3_HOME}/exomeQualityPlots

echo "Input: "
echo "- LG3_HOME=${LG3_HOME:?}"
echo "- LG3_INPUT_ROOT=${LG3_INPUT_ROOT}"
echo "- LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT:?}"
echo "- QC_PLOT_HOME=${QC_PLOT_HOME:?}"
echo "- PROJECT=${PROJECT:?}"
echo "- PATIENT=${PATIENT:?}"
echo "- EMAIL=${EMAIL}"

assert_file_exists "${BEDPATH}"
echo "- BEDPATH=${BEDPATH:?}"

assert_directory_exists "${BAMPATH}"
BAMPATH=$(readlink -e "${BAMPATH}") 
echo "- BAMPATH=${BAMPATH}"
#ls -1 "${BAMPATH}/${PATIENT}"/*.bwa.realigned.rmDups.recal.bam || error "No bam files found in ${BAMPATH}"
ls -1 "${BAMPATH}/${PATIENT}"/*."${RECAL_BAM_EXT}".bam || error "No bam files found in ${BAMPATH}"

make_dir "${WORKDIR}"
WORKDIR=$(readlink -e "${WORKDIR}")
change_dir "${WORKDIR}"
echo "- WORKDIR=${WORKDIR}"

### Prep ENVVARS
QSUB_ENVVARS="LG3_HOME=${LG3_HOME},LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT},EMAIL=${EMAIL},RECAL_BAM_EXT=${RECAL_BAM_EXT}"
QSUB_ENVVARS=$(lg3_qsub_envvar_append_software)
if $qsub_can_set_pwd; then
  QSUB_OPTS="${QSUB_OPTS} -d ${PWD:?}";
fi

## Override the qsub email address?
#if [[ -n ${EMAIL} ]]; then
#  QSUB_OPTS="${QSUB_OPTS} -M ${EMAIL}"
#fi

echo "Qsub extras:"
echo "- QSUB_OPTS=${QSUB_OPTS}"
echo "- QSUB_ENVVARS=${QSUB_ENVVARS}"

### End of ENVVARS

SH_GET_COV=${QC_PLOT_HOME}/get_coverage.sh
assert_file_executable "${SH_GET_COV}"

## Short PatientID
PN=${PATIENT/atient/}
# shellcheck disable=SC2086
qsub ${QSUB_OPTS} -N QC2_${PN} -v "${QSUB_ENVVARS},patient=${PATIENT},bedpath=${BEDPATH},bampath=${BAMPATH}/${PATIENT}" "${SH_GET_COV}"

echo "[$(date +'%Y-%m-%d %H:%M:%S %Z')] END: $PROGRAM"
