#!/bin/bash
ILIST=/home/jocostello/shared/LG3_Pipeline/resources/SeqCap_EZ_Exome_v3_capture.interval_list
PBS=/home/jocostello/shared/LG3_Pipeline/Recal_merge_fixmate.pbs

D=/costellolab/data1/jocostello/LG3/exomes

PATIENT=Patient454
NORMAL=Z00692
SUFF=trim.bwa.sorted.bam
MERGE=/data/jocostello/tmp/$PATIENT

CNT=0
for N in `seq 692 702`
do
	let CNT++
	B=$D/Z00$N/Z00$N.$SUFF
 	if [ ! -f $B ]; then
      echo "ABORT: Can't open $B !"
      exit 1
   fi
   echo "Found $B"
   BAMS=${BAMS}:$B
done
## Clip first char (:)
BAMS=$(echo $BAMS | cut -c2-)
echo "Total BAMS: $CNT"
echo "$BAMS"

qsub -N Rec_$PATIENT -v MERGE=$MERGE,BAMS=$BAMS,NORMAL=$NORMAL,PATIENT=$PATIENT,ILIST=$ILIST $PBS
