#!/bin/bash

LG3_HOME=${LG3_HOME:-/home/jocostello/shared/LG3_Pipeline}
LG3_TEST_DATA_DIR=/costellolab/data1/ismirnov/tmp
EMAIL=${EMAIL:-ivan.smirnov@ucsf.edu}

## Location of links to FASTQ.gz files
RAW=${LG3_TEST_DATA_DIR}
PBS=${LG3_HOME}/trim_galore.pbs

echo "ETA ~4h"

QTY=20

for N in 599 600 601
do
   Z=Z00${N}
   if [ ! -r $RAW/${Z}_R1.fastq.gz ] || [ ! -r $RAW/${Z}_R1.fastq.gz ]; then
      echo "ERROR: Can't open $Z in $RAW"
   else
      echo "Submitting $Z: quality $QTY ..."
      qsub -N trim${QTY}_$Z -M "${EMAIL}" -v FASTQ1=$RAW/${Z}_R1.fastq.gz,FASTQ2=$RAW/${Z}_R2.fastq.gz,PREFIX=$Z,QTY=$QTY "$PBS"
   fi
done

