#!/bin/bash

PROGRAM=${BASH_SOURCE[0]}
echo "[$(date +'%Y-%m-%d %H:%M:%S %Z')] BEGIN: $PROGRAM"
echo "Call: ${BASH_SOURCE[*]}"
echo "Script: $PROGRAM"
echo "Arguments: $*"

LG3_HOME=${LG3_HOME:?}
LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT:-output}
LG3_INPUT_ROOT=${LG3_INPUT_ROOT:-${LG3_OUTPUT_ROOT}}
PROJECT=${PROJECT:-LG3}
PATIENT=${PATIENT:-Patient157t10}
CONV=${CONV:-patient_ID_conversions.tsv}
SAMPLES=${SAMPLES:-$(grep -w "${PATIENT}" "${CONV}" | cut -f1 | tr '\n' ' ')}
LG3_CHASTITY_FILTERING=${LG3_CHASTITY_FILTERING:-false}
EMAIL=${EMAIL:?}

## Requires absolute path 
LG3_HOME=$(readlink -e "$LG3_HOME")
LG3_OUTPUT_ROOT=$(readlink -e "$LG3_OUTPUT_ROOT")

echo "Input:"
echo "- LG3_HOME=${LG3_HOME:?}"
echo "- LG3_INPUT_ROOT=${LG3_INPUT_ROOT:?}"
echo "- LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT:?}"
echo "- EMAIL=${EMAIL}"
echo "- PROJECT=${PROJECT:?}"
echo "- PATIENT=${PATIENT:?}"
echo "- SAMPLES=${SAMPLES:?}"
echo "- LG3_CHASTITY_FILTERING=${LG3_CHASTITY_FILTERING}"

[[ "${PATIENT}" == *[_]* ]] && { echo "ERROR: 'PATIENT' must not contain underscores: ${PATIENT}"; exit 1; }

QSUB_ENVVARS="LG3_HOME=${LG3_HOME},LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT},EMAIL=${EMAIL}"
QSUB_OPTS="${QSUB_OPTS} -d ${PWD:?}"

## Override the qsub email address?
if [[ -n ${EMAIL} ]]; then
  QSUB_OPTS="${QSUB_OPTS} -M ${EMAIL}"
fi

echo "Qsub extras:"
echo "- QSUB_OPTS=${QSUB_OPTS}"
echo "- QSUB_ENVVARS=${QSUB_ENVVARS}"

PBS=${LG3_HOME}/Align_fastq.pbs
[[ -f "$PBS" ]] || { echo "File not found: ${PBS}"; exit 1; }


for SAMPLE in ${SAMPLES}
do
  FASTQ1=${LG3_INPUT_ROOT}/${PROJECT}/trim/${SAMPLE}-trim/${SAMPLE}-trim_R1.fastq.gz
  FASTQ2=${LG3_INPUT_ROOT}/${PROJECT}/trim/${SAMPLE}-trim/${SAMPLE}-trim_R2.fastq.gz

  ## Requires absolute path 
  FASTQ1=$(readlink -e "$FASTQ1")
  FASTQ2=$(readlink -e "$FASTQ2")
  
  ## Expected Location of aligned BAMs
  ALIGNED=${LG3_OUTPUT_ROOT}/${PROJECT}/exomes/${SAMPLE}

  if [ ! -r "${FASTQ1}" ] || [ ! -r "${FASTQ2}" ]; then
    echo "ERROR: Can't open $SAMPLE from ${LG3_INPUT_ROOT}/"
  else
    if [ -f "${ALIGNED}/${SAMPLE}.trim.bwa.sorted.bam" ]; then
      echo "WARNING: already aligned: $ALIGNED/${SAMPLE}.trim.bwa.sorted.bam"
      echo "Skipping $SAMPLE ..."
    else
      echo "Submitting $SAMPLE ..."
      # shellcheck disable=SC2086
      qsub ${QSUB_OPTS} -N Align_$SAMPLE -v "${QSUB_ENVVARS},FASTQ1=${FASTQ1},FASTQ2=${FASTQ2},SAMPLE=${SAMPLE},LG3_CHASTITY_FILTERING=${LG3_CHASTITY_FILTERING},PROJECT=${PROJECT}" "${PBS}"
    fi
  fi
done

echo "[$(date +'%Y-%m-%d %H:%M:%S %Z')] END: $PROGRAM"
