#!/bin/bash

# shellcheck disable=SC1091
source "${LG3_HOME:?}/scripts/utils.sh"
source_lg3_conf

assert_pwd

PROGRAM=${BASH_SOURCE[0]}
echo "[$(date +'%Y-%m-%d %H:%M:%S %Z')] BEGIN: $PROGRAM"
echo "Call: ${BASH_SOURCE[*]}"
echo "Script: $PROGRAM"
echo "Arguments: $*"

LG3_HOME=${LG3_HOME:?}
LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT:-output}
LG3_INPUT_ROOT=${LG3_INPUT_ROOT:-${LG3_OUTPUT_ROOT}}
PROJECT=${PROJECT:-LG3}
CONV=${CONV:-patient_ID_conversions.tsv}
PATIENT=${PATIENT:-Patient157t10}
SAMPLES=${SAMPLES:-$(grep -P "\\t${PATIENT}\\t" "${CONV}" | cut -f1 | tr '\n' ' ')}
NORMAL=${NORMAL:-$(grep -P "\\t${PATIENT}\\t" "${CONV}" | grep -w "Normal" | cut -f 1)}
ILIST=${ILIST:-${LG3_HOME}/resources/SeqCap_EZ_Exome_v3_capture.interval_list}
EMAIL=${EMAIL:?}

## Requires absolute path 
LG3_HOME=$(readlink -e "$LG3_HOME")
LG3_OUTPUT_ROOT=$(readlink -e "$LG3_OUTPUT_ROOT")

echo "Input:"
echo "- LG3_HOME=${LG3_HOME:?}"
echo "- LG3_INPUT_ROOT=${LG3_INPUT_ROOT:?}"
echo "- LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT:?}"
echo "- EMAIL=${EMAIL}"
echo "- SAMPLES=${SAMPLES:?}"
echo "- NORMAL=${NORMAL:?}"
echo "- PATIENT=${PATIENT:?}"
echo "- ILIST=${ILIST:?}"

assert_patient_name "${PATIENT}"

assert_file_exists "${ILIST}"
ILIST=$(readlink -e "$ILIST")

## Assert that NORMAL is one of the SAMPLES
echo "${SAMPLES}" | grep -q -P "(^|\\t| )${NORMAL}(\\t| |$)" || error "NORMAL '${NORMAL}' is not part of SAMPLES: ${SAMPLES}"


QSUB_ENVVARS="LG3_HOME=${LG3_HOME},LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT},EMAIL=${EMAIL},PROJECT=${PROJECT}"
QSUB_OPTS="${QSUB_OPTS} -d ${PWD:?}"

## Override the qsub email address?
if [[ -n ${EMAIL} ]]; then
  QSUB_OPTS="${QSUB_OPTS} -M ${EMAIL}"
fi

echo "Qsub extras:"
echo "- QSUB_OPTS=${QSUB_OPTS}"
echo "- QSUB_ENVVARS=${QSUB_ENVVARS}"

PBS=${LG3_HOME}/Recal_pass2.pbs
assert_file_exists "${PBS}"

D=${LG3_INPUT_ROOT}/${PROJECT}/exomes_recal
assert_directory_exists "${D}"
D=$(readlink -e "$D") ## requires absolute path

assert_directory_exists "${D}/${PATIENT}"
[[ -d "$D/${PATIENT}.before.merge" ]] && warn "Directory found: ${D}/${PATIENT}.before.merge"

echo "Renaming $D/${PATIENT} to $D/${PATIENT}.before.merge"
mv "$D/${PATIENT}" "$D/${PATIENT}.before.merge" || warn "No directory $D/${PATIENT}"

SUFF=bwa.realigned.rmDups.recal.bam

CNT=0
for SAMPLE in ${SAMPLES}
do
   ((CNT++))
   B=$D/${PATIENT}.before.merge/${SAMPLE}.$SUFF
   assert_file_exists "${B}"
   echo "Found $B"
   BAMS=${BAMS}:$B
done
## Clip first char (:)
BAMS=$(echo "$BAMS" | cut -c2-)
echo "Total BAMS: $CNT"
echo "$BAMS"

# shellcheck disable=SC2086
qsub ${QSUB_OPTS} -N Rec2_$PATIENT -v "${QSUB_ENVVARS},BAMS=${BAMS},NORMAL=${NORMAL},PATIENT=${PATIENT},ILIST=${ILIST}" "$PBS"

echo "[$(date +'%Y-%m-%d %H:%M:%S %Z')] END: $PROGRAM"
