#!/bin/bash

# shellcheck disable=SC1072,SC1073
source "${LG3_HOME:?}/scripts/utils.sh"
source_lg3_conf

assert_pwd

PROGRAM=${BASH_SOURCE[0]}
echo "[$(date +'%Y-%m-%d %H:%M:%S %Z')] BEGIN: $PROGRAM"
echo "Call: ${BASH_SOURCE[*]}"
echo "Script: $PROGRAM"
echo "Arguments: $*"

LG3_HOME=${LG3_HOME:?}
LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT:-output}
LG3_INPUT_ROOT=${LG3_INPUT_ROOT:-rawdata}
PROJECT=${PROJECT:-LG3}
PATIENT=${PATIENT:-Patient157t10}
CONV=${CONV:-patient_ID_conversions.tsv}
LG3_CHASTITY_FILTERING=${LG3_CHASTITY_FILTERING:-false}
EMAIL=${EMAIL:?}
LG3_DEBUG=true

## Requires absolute path 
LG3_HOME=$(readlink -e "$LG3_HOME")
LG3_OUTPUT_ROOT=$(readlink -e "$LG3_OUTPUT_ROOT")

echo "Input:"
echo "- LG3_HOME=${LG3_HOME:?}"
echo "- LG3_INPUT_ROOT=${LG3_INPUT_ROOT:?}"
#echo "- LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT:?}"
echo "- EMAIL=${EMAIL}"
echo "- PROJECT=${PROJECT:?}"
echo "- PATIENT=${PATIENT:?}"
echo "- CONV=${CONV:?}"
echo "- LG3_CHASTITY_FILTERING=${LG3_CHASTITY_FILTERING}"

assert_patient_name "${PATIENT}"

SAMPLES=${SAMPLES:-$(grep -P "\\t${PATIENT}\\t" "${CONV}" | cut -f1 | tr '\n' ' ')}
echo "- SAMPLES=${SAMPLES:?}"

PBS=${LG3_HOME}/Align_fastq.pbs
assert_file_exists "${PBS}"


for SAMPLE in ${SAMPLES}
do
  FASTQ1=${LG3_INPUT_ROOT}/${SAMPLE}_R1.fastq.gz
  FASTQ2=${LG3_INPUT_ROOT}/${SAMPLE}_R2.fastq.gz

  ## Requires absolute path 
  FASTQ1=$(readlink -e "$FASTQ1")
  FASTQ2=$(readlink -e "$FASTQ2")
  
  ## Expected Location of aligned BAMs
  ALIGNED=${LG3_OUTPUT_ROOT}/${PROJECT}/exomes/${SAMPLE}

  if [ ! -r "${FASTQ1}" ] || [ ! -r "${FASTQ2}" ]; then
    warn "Can't open FastQ file for $SAMPLE from ${LG3_INPUT_ROOT}/"
  else
    if [ -f "${ALIGNED}/${SAMPLE}.*.sorted.bam" ]; then
      warn "${SAMPLE} is aligned (${ALIGNED}/${SAMPLE}.*.bam). Skipping ..."
    else
      echo "Submitting $SAMPLE ..."
      #qsub ${QSUB_OPTS} -N Align_$SAMPLE -v "${QSUB_ENVVARS},FASTQ1=${FASTQ1},FASTQ2=${FASTQ2},SAMPLE=${SAMPLE},LG3_CHASTITY_FILTERING=${LG3_CHASTITY_FILTERING},PROJECT=${PROJECT}" "${PBS}"

      sbatch --mail-user="${EMAIL}" --mail-type=END,FAIL \
        --job-name="Aln-${SAMPLE}" \
        --output="Align-${SAMPLE}.out" \
        --error="Align-${SAMPLE}.err" \
        --export=ALL,LG3_HOME="${LG3_HOME}",LG3_OUTPUT_ROOT="${LG3_OUTPUT_ROOT}",SAMPLE="${SAMPLE}",FASTQ1="${FASTQ1}",FASTQ2="${FASTQ2}",LG3_CHASTITY_FILTERING="${LG3_CHASTITY_FILTERING}",PROJECT="${PROJECT}",LG3_DEBUG="${LG3_DEBUG}" \
        --nodes=1 \
        --ntasks=12 \
        --mem=64G \
        --time=9-06:00:00 \
       "${PBS}" 
    fi
  fi
done

echo "[$(date +'%Y-%m-%d %H:%M:%S %Z')] END: $PROGRAM"
