#!/bin/bash
D=/costellolab/jocostello/LG3/exomes

PATIENT=Patient450
NORMAL=Z00667
SUFF=trim.bwa.sorted.bam
MERGE=/data/jocostello/tmp/$PATIENT

CNT=0
for N in `seq 667 680`
do
   let CNT++
   B=$D/Z00$N/Z00$N.$SUFF
   if [ ! -f $B ]; then
      echo "ABORT: Can't open $B !"
      exit 1
   fi
   echo "Found $B"
   BAMS=${BAMS}:$B
done
## Clip first char (:)
BAMS=$(echo $BAMS | cut -c2-)
echo "Total BAMS: $CNT"
echo "$BAMS"

ILIST=/home/jocostello/shared/LG3_Pipeline/resources/SeqCap_EZ_Exome_v3_capture.interval_list
PBS=/home/jocostello/shared/LG3_Pipeline/Recal_merge1.pbs

qsub -N Recal_$PATIENT -v MERGE=$MERGE,BAMS=$BAMS,NORMAL=$NORMAL,PATIENT=$PATIENT,ILIST=$ILIST $PBS
