#!/bin/bash

# shellcheck source=scripts/utils.sh
source "${LG3_HOME:?}/scripts/utils.sh"
source_lg3_conf

assert_pwd

PROGRAM=${BASH_SOURCE[0]}
echo "[$(date +'%Y-%m-%d %H:%M:%S %Z')] BEGIN: $PROGRAM"
echo "Call: ${BASH_SOURCE[*]}"
echo "Script: $PROGRAM"
echo "Arguments: $*"

LG3_HOME=${LG3_HOME:?}
LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT:-output}
LG3_INPUT_ROOT=${LG3_INPUT_ROOT:-${LG3_OUTPUT_ROOT}}
#QC_PLOT_HOME=${QC_PLOT_HOME:-exomeQualityPlots}
EMAIL=${EMAIL:?}
PROJECT=${PROJECT:-LG3}
CONV=${CONV:-patient_ID_conversions.tsv}
PATIENT=${PATIENT:-Patient157t10}
REF=${LG3_HOME}/resources/UCSC_HG19_Feb_2009/hg19.fa
MUTATIONFILE=${LG3_INPUT_ROOT}/${PROJECT}/MutInDel/${PATIENT}.snvs.indels.filtered.overlaps.txt
BAMPATH=${LG3_INPUT_ROOT}/${PROJECT}/exomes_recal
WORKDIR=${LG3_OUTPUT_ROOT}/${PROJECT}/exome_QC_plots/${PATIENT}

## Requires absolute path
LG3_HOME=$(readlink -e "$LG3_HOME")
LG3_OUTPUT_ROOT=$(readlink -e "$LG3_OUTPUT_ROOT")
QC_PLOT_HOME=${LG3_HOME}/exomeQualityPlots

echo "Input: "
echo "- LG3_HOME=${LG3_HOME:?}"
echo "- LG3_INPUT_ROOT=${LG3_INPUT_ROOT}"
echo "- LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT:?}"
echo "- QC_PLOT_HOME=${QC_PLOT_HOME:?}"
echo "- PROJECT=${PROJECT:?}"
echo "- PATIENT=${PATIENT:?}"
echo "- EMAIL=${EMAIL}"

## Assert that the qualityinfo file exists and not empty
#qualityinfo=${LG3_OUTPUT_ROOT}/${PROJECT}/QC_plots/${PATIENT}/${PATIENT}.qualityinfo.tmp
qualityinfo=${WORKDIR}/${PATIENT}.qualityinfo.tmp
assert_file_exists "${qualityinfo}"
echo "- qualityinfo=${qualityinfo}"

## Assert that the genome reference file exists
assert_file_exists "${REF}"
echo "- REF=${REF}"

## Assert that the conversion file exists
assert_file_exists "${CONV}"
CONV=$(readlink -e "${CONV}")
echo "- CONV=${CONV}"

## Assert that the mutation file exists
assert_file_exists "${MUTATIONFILE}"
MUTATIONFILE=$(readlink -e "${MUTATIONFILE}")
echo "- MUTATIONFILE=${MUTATIONFILE}"

assert_directory_exists "${BAMPATH}"
BAMPATH=$(readlink -e "${BAMPATH}") ## requires absolute path
ls -1 "${BAMPATH}/${PATIENT}/"*.bwa.realigned.rmDups.recal.bam || error "No bam files found in ${BAMPATH}"
echo "- BAMPATH=${BAMPATH}"

make_dir "${WORKDIR}"
WORKDIR=$(readlink -e "${WORKDIR}")
change_dir "${WORKDIR}"
echo "- WORKDIR=${WORKDIR}"

### Prep ENVVARS
QSUB_ENVVARS="LG3_HOME=${LG3_HOME},LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT},EMAIL=${EMAIL},RECAL_BAM_EXT=${RECAL_BAM_EXT}"
QSUB_ENVVARS=$(lg3_qsub_envvar_append_software)
if $qsub_can_set_pwd; then
  QSUB_OPTS="${QSUB_OPTS} -d ${PWD:?}";
fi

## Override the qsub email address?
if [[ -n ${EMAIL} ]]; then
  QSUB_OPTS="${QSUB_OPTS} -M ${EMAIL}"
fi

echo "Qsub extras:"
echo "- QSUB_OPTS=${QSUB_OPTS}"
echo "- QSUB_ENVVARS=${QSUB_ENVVARS}"

### End of ENVVARS

SH_EXOME_QC=${QC_PLOT_HOME}/exome_quality.sh
assert_file_executable "${SH_EXOME_QC}"

PN=${PATIENT/Patient/Pat} ## Abbreviated PatientID
qsub "${QSUB_OPTS}" -l vmem=96gb -e "_QC3_${PATIENT}.err" -o "_QC3_${PATIENT}.out" -N "QC3_${PN}" -m ae -v "${QSUB_ENVVARS},mutationfile=${MUTATIONFILE},reffasta=$REF,patient=${PATIENT},conversionfile=${CONV},bampath=${BAMPATH},scriptpath=${QC_PLOT_HOME}" "${SH_EXOME_QC}"

echo "[$(date +'%Y-%m-%d %H:%M:%S %Z')] END: $PROGRAM"
