#!/bin/bash

# shellcheck disable=SC1072,SC1073
source "${LG3_HOME:?}/scripts/utils.sh"
source_lg3_conf

assert_pwd

PROGRAM=${BASH_SOURCE[0]}
echo "[$(date +'%Y-%m-%d %H:%M:%S %Z')] BEGIN: $PROGRAM"
echo "Call: ${BASH_SOURCE[*]}"
echo "Script: $PROGRAM"
echo "Arguments: $*"

LG3_HOME=${LG3_HOME:?}
LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT:-output}
LG3_INPUT_ROOT=${LG3_INPUT_ROOT:-${LG3_OUTPUT_ROOT}}
EMAIL=${EMAIL:?}
PATIENT=${PATIENT:-Patient157t10}
PROJECT=${PROJECT:-LG3}
CONV=${CONV:-patient_ID_conversions.tsv}
LG3_DEBUG=true

## Requires absolute path 
LG3_HOME=$(readlink -e "$LG3_HOME")
LG3_OUTPUT_ROOT=$(readlink -e "$LG3_OUTPUT_ROOT")

echo "Input:"
echo "- LG3_HOME=${LG3_HOME:?}"
echo "- LG3_INPUT_ROOT=${LG3_INPUT_ROOT:?}"
echo "- LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT:?}"
echo "- EMAIL=${EMAIL}"
echo "- PATIENT=${PATIENT:?}"
echo "- PROJECT=${PROJECT:?}"
echo "- CONV=${CONV:?}"
echo "- LG3_DEBUG=${LG3_DEBUG}"

assert_patient_name "${PATIENT}"

assert_file_exists "${CONV}"
CONV=$(readlink -e "$CONV")

SH_MUTECT2_SUBMIT=${LG3_HOME}/scripts/mutect2_submit.sh
assert_file_executable "${SH_MUTECT2_SUBMIT}"

echo -n "Submitting jobs for $PATIENT "
date

## Assert that input files exist
D=${LG3_OUTPUT_ROOT}/${PROJECT}/exomes_recal/${PATIENT}
assert_directory_exists "${D}"

"${SH_MUTECT2_SUBMIT}" "${PATIENT}" "${CONV}" "${PROJECT}" || error "${SH_MUTECT2_SUBMIT} failed"

echo "[$(date +'%Y-%m-%d %H:%M:%S %Z')] END: $PROGRAM"
