#!/bin/bash

# shellcheck disable=SC1091
source "${LG3_HOME:?}/scripts/utils.sh"
source_lg3_conf

assert_pwd

PROGRAM=${BASH_SOURCE[0]}
echo "[$(date +'%Y-%m-%d %H:%M:%S %Z')] BEGIN: $PROGRAM"
echo "Call: ${BASH_SOURCE[*]}"
echo "Script: $PROGRAM"
echo "Arguments: $*"

LG3_HOME=${LG3_HOME:?}
LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT:-output}
LG3_INPUT_ROOT=${LG3_INPUT_ROOT:-${LG3_OUTPUT_ROOT}}
PROJECT=${PROJECT:-LG3}
CONV=${CONV:-patient_ID_conversions.tsv}
PATIENT=${PATIENT:-Patient157t10}
EMAIL=${EMAIL:?}
LG3_DEBUG=true

## Requires absolute path 
LG3_HOME=$(readlink -e "$LG3_HOME")
LG3_OUTPUT_ROOT=$(readlink -e "$LG3_OUTPUT_ROOT")

echo "Input:"
echo "- LG3_HOME=${LG3_HOME:?}"
echo "- LG3_INPUT_ROOT=${LG3_INPUT_ROOT:?}"
echo "- LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT:?}"
echo "- EMAIL=${EMAIL}"
echo "- PATIENT=${PATIENT:?}"
echo "- PROJECT=${PROJECT:?}"
echo "- CONV=${CONV:?}"

assert_patient_name "${PATIENT}"

assert_file_exists "${CONV}"

SH_CHK_PINDEL=${LG3_HOME}/scripts/chk_pindel.sh
assert_file_executable "${SH_CHK_PINDEL}"

SH_CHK_MUTDET=${LG3_HOME}/scripts/chk_mutdet.sh
assert_file_executable "${SH_CHK_MUTDET}"

"${SH_CHK_PINDEL}" "${PROJECT}" "${PATIENT}" || error "${SH_CHK_PINDEL} failed"
"${SH_CHK_MUTDET}" "${PROJECT}" "${PATIENT}" || error "${SH_CHK_MUTDET} failed"

PBS=${LG3_HOME}/post_mutect_pindel.pbs
assert_file_exists "${PBS}"

## Short PatientID
PAT=${PATIENT/atient/}
sbatch --mail-user="${EMAIL}" --mail-type=END,FAIL \
	--job-name="${PAT}_comb" \
	--output="${PAT}_comb.out" \
	--error="${PAT}_comb.err" \
	--export=ALL,LG3_HOME="${LG3_HOME}",LG3_INPUT_ROOT="${LG3_INPUT_ROOT}",LG3_OUTPUT_ROOT="${LG3_OUTPUT_ROOT}",PROJECT="${PROJECT}",PATIENT="${PATIENT}",CONV="${CONV}",LG3_DEBUG="${LG3_DEBUG}" \
	--nodes=1 \
	--ntasks=1 \
	--mem=64G \
	--time=9-06:00:00 \
	"${PBS}"

echo "[$(date +'%Y-%m-%d %H:%M:%S %Z')] END: $PROGRAM"
