#!/bin/bash

PROGRAM=${BASH_SOURCE[0]}
echo "[$(date +'%Y-%m-%d %H:%M:%S %Z')] BEGIN: $PROGRAM"
echo "Call: ${BASH_SOURCE[*]}"
echo "Script: $PROGRAM"
echo "Arguments: $*"

LG3_HOME=${LG3_HOME:-/home/jocostello/shared/LG3_Pipeline}
LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT:-output}
LG3_INPUT_ROOT=${LG3_INPUT_ROOT:-${LG3_OUTPUT_ROOT}}
EMAIL=${EMAIL:?}
PROJECT=${PROJECT:-LG3}
PATIENT=${PATIENT:-Patient157t10}
BEDPATH=${BEDPATH:-${LG3_HOME}/resources/SeqCap_EZ_Exome_v3_capture.bed}
BAMPATH=${LG3_INPUT_ROOT}/${PROJECT}/exomes_recal

## Requires absolute path
LG3_HOME=$(readlink -e "$LG3_HOME")
LG3_OUTPUT_ROOT=$(readlink -e "$LG3_OUTPUT_ROOT")

echo "Input: "
echo "- LG3_HOME=${LG3_HOME:?}"
echo "- LG3_INPUT_ROOT=${LG3_INPUT_ROOT}"
echo "- LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT:?}"
echo "- PROJECT=${PROJECT:?}"
echo "- PATIENT=${PATIENT:?}"
echo "- EMAIL=${EMAIL}"

[[ -f "${BEDPATH}" ]] || { echo "ERROR: File not found: ${BEDPATH}"; exit 1; }
echo "- BEDPATH=${BEDPATH:?}"

[[ -d "${BAMPATH}" ]] || { echo "ERROR: Directory not found: ${BAMPATH}"; exit 1; }
BAMPATH=$(readlink -e "${BAMPATH}") 
echo "- BAMPATH=${BAMPATH}"
ls -1 "${BAMPATH}/${PATIENT}"/*.bwa.realigned.rmDups.recal.bam || { echo "ERROR: No bam files found in ${BAMPATH}"; exit 1; }

SCRIPT_A=${LG3_HOME}/scripts/get_coverage.sh
[[ -x "$SCRIPT_A" ]] || { echo "ERROR: File not found or not an executable: ${SCRIPT_A}"; exit 1; }

QSUB_ENVVARS="LG3_HOME=${LG3_HOME},LG3_INPUT_ROOT=${LG3_INPUT_ROOT},LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT}"

PN=${PATIENT/Patient/Pat}
qsub -l vmem=300gb -e "_QC1_${PATIENT}.err" -o "_QC1_${PATIENT}.out" -N "QC1_${PN}" -M "${MAIL}" -m ae -v "${QSUB_ENVVARS},PATIENT=${PATIENT},BEDPATH=${BEDPATH},BAMPATH=${BAMPATH}/${PATIENT}" "${SCRIPT_A}"

echo "[$(date +'%Y-%m-%d %H:%M:%S %Z')] END: $PROGRAM"
