#!/bin/bash

# shellcheck source=scripts/utils.sh
source "${LG3_HOME:?}/scripts/utils.sh"
source_lg3_conf

assert_pwd

rm_if_link(){ [ ! -L "$1" ] || rm -f "$1"; }


PROGRAM=${BASH_SOURCE[0]}
echo "[$(date +'%Y-%m-%d %H:%M:%S %Z')] BEGIN: $PROGRAM"
echo "Call: ${BASH_SOURCE[*]}"
echo "Script: $PROGRAM"
echo "Arguments: $*"

LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT:-output}
LG3_INPUT_ROOT=${LG3_INPUT_ROOT:-${LG3_OUTPUT_ROOT}}

if [ ! -r "${PSCN_HOME:?}" ]; then
   error "PSCN_HOME link is not set! Please clone 'Costello-PSCN-Seq' repo, edit config.yml and 0.setup.R and provide link"
fi
warn "Make sure you edited config.yml and 0.setup.R files in 'Costello-PSCN-Seq' repo!"

PATIENT=${PATIENT:-Patient157t10}
## Assert that the conversion file exists
assert_file_exists "${CONV}"

BAMPATH=${LG3_INPUT_ROOT}/${PROJECT}/exomes_recal/${PATIENT}

echo "Input: "
echo "- LG3_HOME=${LG3_HOME:?}"
echo "- LG3_INPUT_ROOT=${LG3_INPUT_ROOT}"
echo "- LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT:?}"
echo "- PSCN_HOME=${PSCN_HOME:?}"
echo "- PROJECT=${PROJECT:?}"
echo "- PATIENT=${PATIENT:?}"
echo "- CONV=${CONV}"
echo "- BAMPATH=${BAMPATH}"
echo "- EMAIL=${EMAIL}"

echo "Removing symlinks for output"
rm_if_link "${PSCN_HOME}/seqzData" 
rm_if_link "${PSCN_HOME}/pscbsData" 
rm_if_link "${PSCN_HOME}/reports"


## Requires absolute path
#LG3_HOME=$(readlink -e "${LG3_HOME}")
LG3_OUTPUT_ROOT=$(readlink -e "${LG3_OUTPUT_ROOT}")
BAMPATH=$(readlink -e "${BAMPATH}")

echo "Making output directories if needed..."
SEQUENZA_OUT=${LG3_INPUT_ROOT}/${PROJECT}/sequenza/${PATIENT}
make_dir "${SEQUENZA_OUT}"
if [ ! -d "${SEQUENZA_OUT}" ]; then
	error "Directory not created: ${SEQUENZA_OUT}"
fi
PSCBS_OUT=${LG3_INPUT_ROOT}/${PROJECT}/PSCBS/${PATIENT}
make_dir "${PSCBS_OUT}"
PSCN_OUT=${LG3_INPUT_ROOT}/${PROJECT}/PSCN/${PATIENT}
make_dir "${PSCN_OUT}"

SEQUENZA_OUT=$(readlink -e "${SEQUENZA_OUT}")
PSCBS_OUT=$(readlink -e "${PSCBS_OUT}")
PSCN_OUT=$(readlink -e "${PSCN_OUT}")

echo "- SEQUENZA_OUT=${SEQUENZA_OUT:?}"
echo "- PSCBS_OUT=${PSCBS_OUT:?}"
echo "- PSCN_OUT=${PSCN_OUT:?}"

ls -1 "${BAMPATH}/"*."${RECAL_BAM_EXT}.bam" || error "No BAM files found in ${BAMPATH}"

change_dir "${PSCN_HOME}"

module load r/3.4.4
Rscript 0.setup.R

echo "Creating samples.tsv"
echo -e "Patient_ID\\tSample_ID\\tSF\\tKit\\tA0" > sampleData/samples.tsv
grep -P "\\t${PATIENT}\\t" "${CONV}" | awk -v OFS="\\t" '{print $3,$4,$2,"Nimblegen SeqCap EZ Exome v3",$1}' >> sampleData/samples.tsv

cat sampleData/samples.tsv
echo "Total samples: "
wc -l sampleData/samples.tsv

rmdir seqzData
ln -sf "${SEQUENZA_OUT}" seqzData || error "Failed to create a link to ${SEQUENZA_OUT}"

ln -sf "${PSCBS_OUT}" pscbsData || error "Failed to create a link to ${PSCBS_OUT}"

ln -sf "${PSCN_OUT}" reports || error "Failed to create a link to ${PSCN_OUT}"


qsub -d "${PSCN_HOME}" -M "${EMAIL}" -m ae -v "LG3_HOME=${LG3_HOME}" "${LG3_HOME}/PSCN.submit_all.pbs"

echo "[$(date +'%Y-%m-%d %H:%M:%S %Z')] END: $PROGRAM"
