#!/bin/bash

# shellcheck source=scripts/utils.sh
source "${LG3_HOME:?}/scripts/utils.sh"

rm_if_link(){ [ ! -L "$1" ] || rm -f "$1"; }


PROGRAM=${BASH_SOURCE[0]}
echo "[$(date +'%Y-%m-%d %H:%M:%S %Z')] BEGIN: $PROGRAM"
echo "Call: ${BASH_SOURCE[*]}"
echo "Script: $PROGRAM"
echo "Arguments: $*"
LG3_HOME=${LG3_HOME:?}
LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT:-output}
LG3_INPUT_ROOT=${LG3_INPUT_ROOT:-${LG3_OUTPUT_ROOT}}
PSCN_HOME=${LG3_HOME}/Costello-PSCN-Seq

echo "************** Check once 0.setup.R ********************"
cat ${PSCN_HOME}/0.setup.R
echo "************** Check config.yml ********************"
cat ${PSCN_HOME}/config.yml
echo "************** Check BAM path ! ********************"
ls ${PSCN_HOME}/bamData/*
echo "****************************************************"

EMAIL=${EMAIL:?}
PROJECT=${PROJECT:-LG3}
#CONV=${CONV:-patient_ID_conversions.tsv}
PATIENT=${PATIENT:-Patient157t10}
#PAT_MASTER=${PAT_MASTER:-samples_last_X00216.tsv}
PAT_MASTER=${LG3_HOME}/samples_last_X00216.tsv
BAMPATH=${LG3_INPUT_ROOT}/${PROJECT}/exomes_recal/${PATIENT}
echo "- BAMPATH=${BAMPATH:?}"

## Requires absolute path
LG3_HOME=$(readlink -e "${LG3_HOME}")
BAMPATH=$(readlink -e "${BAMPATH}")
echo "- BAMPATH=${BAMPATH:?}"
LG3_OUTPUT_ROOT=$(readlink -e "${LG3_OUTPUT_ROOT}")
PAT_MASTER=$(readlink -e "${PAT_MASTER}")

echo "Input: "
echo "- LG3_HOME=${LG3_HOME}"
echo "- PAT_MASTER=${PAT_MASTER}"
echo "- LG3_INPUT_ROOT=${LG3_INPUT_ROOT}"
echo "- LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT}"
echo "- PSCN_HOME=${PSCN_HOME}"
echo "- PROJECT=${PROJECT}"
echo "- PATIENT=${PATIENT}"
echo "- EMAIL=${EMAIL}"

## Assert that the conversion file exists
assert_file_exists "${CONV}"
CONV=$(readlink -e "${CONV}")
echo "- CONV=${CONV}"

ls -1 "${BAMPATH}/"*.bwa.realigned.rmDups.recal.bam || error "No BAM files found in ${BAMPATH}"


change_dir "${PSCN_HOME}"

#module load r/3.4.4
#Rscript 0.setup.R

echo "Creating samples.tsv"
head -n 1 ${PAT_MASTER} > sampleData/samples.tsv
grep -P "${PATIENT}\\t" "${PAT_MASTER}" >> sampleData/samples.tsv

#echo -e "Patient_ID\\tSample_ID\\tSF Kit\\tA0" > sampleData/samples.tsv
#grep -P "\\t${PATIENT}\\t" ${CONV} | awk -v OFS="\t" '{print $3,$4,$2,"Agilent SureSelect Human All Exon 50MB",$1}' >> sampleData/samples.tsv
#grep -P "\\t${PATIENT}\\t" ${CONV} | awk -v OFS="\t" '{print $3,$4,$2,"Nimblegen SeqCap EZ Exome v3",$1}' >> sampleData/samples.tsv
#grep -P "\\t${PATIENT}\\t" ${CONV} | awk -v OFS="\t" '{print $3,$4,$2,"Xgen Exome Research Panel",$1}' >> sampleData/samples.tsv

echo "************** Check samples ********************"
cat sampleData/samples.tsv
echo "Total samples: "
wc -l sampleData/samples.tsv
echo "================================================="

qsub -d "${PSCN_HOME}" -M "${EMAIL}" -m ae -v "LG3_HOME=${LG3_HOME},PROJECT=${PROJECT}" "${LG3_HOME}/PSCN.submit_1-5.pbs"

echo "[$(date +'%Y-%m-%d %H:%M:%S %Z')] END: $PROGRAM"
